#include "kachakacha/app/CommandCatalog.h"
#include <algorithm>
namespace kachakacha::v2::app {
std::string_view SelectionPredicateNameJa(SelectionPredicate value) noexcept
{
    switch (value) {
    case SelectionPredicate::Always: return "常に使えます。";
    case SelectionPredicate::HasDocument: return "文書がありません。";
    case SelectionPredicate::HasUndo: return "戻せる操作がありません。";
    case SelectionPredicate::HasRedo: return "やり直せる操作がありません。";
    case SelectionPredicate::HasVisibleGeometry: return "見えているものがありません。";
    case SelectionPredicate::OneWorkPlane: return "作業平面を1つ選んでください。";
    case SelectionPredicate::OnePlanarFaceOrWorkPlane: return "平らな面か作業平面を1つ選んでください。";
    case SelectionPredicate::ZeroOrOneGroup: return "グループは1つまで選べます。";
    case SelectionPredicate::OneOrMoreWires: return "ワイヤーを1つ以上選んでください。";
    case SelectionPredicate::TwoOrMoreWires: return "ワイヤーを2つ以上選んでください。";
    case SelectionPredicate::TwoWireChains: return "鎖を2つ選んでください。";
    case SelectionPredicate::OneClosedProfile: return "閉じた輪郭を1つ選んでください。";
    case SelectionPredicate::OneOrMoreClosedProfiles: return "閉じた輪郭を1つ以上選んでください。";
    case SelectionPredicate::OnePart: return "部品を1つ選んでください。";
    case SelectionPredicate::TwoParts: return "部品を2つ選んでください。";
    case SelectionPredicate::OneDerivedEntity: return "派生したものを1つ選んでください。";
    case SelectionPredicate::OneFabricationModel: return "製作モデルを1つ選んでください。";
    case SelectionPredicate::OneFabricationPanel: return "部材を1つ選んでください。";
    case SelectionPredicate::OneOrMorePatterns: return "型紙を1つ以上選んでください。";
    case SelectionPredicate::OneOrMoreSelectedCurves: return "曲線を1つ以上選んでください。";
    case SelectionPredicate::OnePartOrSurface: return "部品か形状ガイドを1つ選んでください。";
    case SelectionPredicate::OneOrMoreGuideSurfaces: return "形状ガイドの面を1つ以上選んでください。";
    case SelectionPredicate::OneOrMoreWiresOrGuideSurfaces: return "ワイヤーか形状ガイドの面を1つ以上選んでください。";
    case SelectionPredicate::OneGuideRow: return "役割表の行を1つ選んでください。";
    case SelectionPredicate::OneOrMoreGuideRows: return "役割表に行を1つ以上入れてください。";
    case SelectionPredicate::WiresAndOneGuideSurface: return "ワイヤーを1つ以上と、落とす先の形状ガイドの面を1つ選んでください。";
    case SelectionPredicate::WiresAndTwoOrMoreGuideSurfaces: return "ワイヤーを1つ以上と、落とす先の形状ガイドの面を2つ以上選んでください。";
    case SelectionPredicate::OneGuideSurfaceAndOneWorkPlane: return "形状ガイドの面を1つと、相手の作業平面を1つ選んでください。";
    case SelectionPredicate::OneOrMoreHideable: return "線・部品・面のどれかを選んでください。";
    }
    return "";
}

const std::vector<CommandDescriptor>& CommandCatalog()
{
    // 並びは docs/v2/command-catalog.md と同じ順。決定的であること。
    static const std::vector<CommandDescriptor> table = {
        {"file.new", "新規", CommandMode::Instant, "new", "Ctrl+N",
            SelectionPredicate::HasDocument, "文書がありません。",
            "新しい文書を作ります。保存していない変更があれば先に確かめます。", true,
            {"AT-DOC-001"}},
        {"file.open", "開く", CommandMode::Dialog, "open", "Ctrl+O",
            SelectionPredicate::Always, "",
            "保存した文書を開きます。読めない中身なら、いまの文書はそのままにします。", true,
            {"AT-EXP-001", "AT-EXP-002", "AT-EXP-003"}},
        {"file.save", "保存", CommandMode::Instant, "save", "Ctrl+S",
            SelectionPredicate::HasDocument, "文書がありません。",
            "いまの文書を保存します。途中で失敗しても元のファイルは残ります。", false,
            {"AT-EXP-004"}},
        {"file.save_as", "名前を付けて保存", CommandMode::Dialog, "save_as", "Ctrl+Shift+S",
            SelectionPredicate::HasDocument, "文書がありません。",
            "名前を付けて保存します。", false,
            {"AT-EXP-004"}},
        {"edit.undo", "元に戻す", CommandMode::Instant, "undo", "Ctrl+Z",
            SelectionPredicate::HasUndo, "戻せる操作がありません。",
            "直前の操作を戻します。", true,
            {"AT-DOC-005"}},
        {"edit.redo", "やり直す", CommandMode::Instant, "redo", "Ctrl+Y",
            SelectionPredicate::HasRedo, "やり直せる操作がありません。",
            "戻した操作をやり直します。", true,
            {"AT-DOC-005"}},
        {"edit.delete", "削除", CommandMode::Instant, "delete", "Del",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだものを消します。下流があるものは、理由を出して断ります。", true,
            {"AT-DOC-005"}},
        {"view.hide_selected", "選択を隠す", CommandMode::Instant, "hide", "Ctrl+H",
            SelectionPredicate::OneOrMoreHideable, "線・部品・面のどれかを選んでください。",
            "選んだものを画面から隠します。形は消えません。", false,
            {"AT-UIX-010"}},
        {"view.show_all", "すべて表示", CommandMode::Instant, "show_all", "Ctrl+Shift+H",
            SelectionPredicate::HasDocument, "文書がありません。",
            "隠したものを全部出します。", false,
            {"AT-UIX-010"}},
        {"selection.activate", "選択", CommandMode::Tool, "select", "V",
            SelectionPredicate::Always, "",
            "選ぶ道具に戻ります。", false,
            {"AT-UIX-001"}},
        {"measure.open", "測定", CommandMode::Modeless, "measure", "M",
            SelectionPredicate::Always, "",
            "距離や角度を測ります。測った場所から作図点を作れます。", false,
            {"AT-MEA-001", "AT-MEA-002", "AT-MEA-003", "AT-MEA-004", "AT-MEA-005"}},
        {"edit.numeric", "数値で編集", CommandMode::Modeless, "edit_numeric", "",
            SelectionPredicate::Always, "",
            "選んだ作業平面(原点・法線・平面内X)や線(点・中心・軸・半径・角度)の数値を"
            "欄で直します。種類は変わりません。", false,
            {"AT-WIR-001", "AT-UIX-001"}},
        {"view.fit_all", "全体表示", CommandMode::Instant, "fit", "F",
            SelectionPredicate::HasVisibleGeometry, "見えているものがありません。",
            "見えているもの全部が入るように視点を合わせます。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.align_selection", "選択に正対", CommandMode::Instant, "align", "",
            SelectionPredicate::OnePlanarFaceOrWorkPlane, "平らな面か作業平面を1つ選んでください。",
            "選んだ平面に正対します。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.align_workplane", "正対", CommandMode::Instant, "align_workplane", "",
            SelectionPredicate::Always, "",
            "作業中の作図面に正対します(上の帯の「正対」)。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.display_settings", "表示設定", CommandMode::Dialog, "display", "",
            SelectionPredicate::Always, "",
            "線の太さや色などの見え方を変えます。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_all", "設計(すべて出す)", CommandMode::Instant, "stage_all", "Ctrl+1",
            SelectionPredicate::Always, "",
            "グリッドも補助線も出します(V1 の「設計」)。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_no_grid", "グリッドを消す", CommandMode::Instant, "stage_grid",
            "", SelectionPredicate::Always, "",
            "グリッドだけ消します。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_no_construction", "完成形(補助線も消す)", CommandMode::Instant,
            "stage_plain", "Ctrl+2", SelectionPredicate::Always, "",
            "グリッドも補助線も消して、出来上がりだけ見ます(V1 の「完成形」)。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_selection_only", "選択だけ", CommandMode::Instant,
            "stage_selection", "Ctrl+3", SelectionPredicate::Always, "",
            "選んでいるものだけを出します(V1 の「選択だけ」)。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"entity.rename", "名前を変える", CommandMode::Instant, "rename", "F2",
            SelectionPredicate::Always, "",
            "一覧で選んでいるものの名前を変えます。形は変わりません。", false,
            {"AT-DOC-005"}},
        {"snap.toggle", "スナップ", CommandMode::Instant, "snap", "F3",
            SelectionPredicate::Always, "",
            "吸着を入り切りします。", false,
            {"AT-UIX-004"}},
        {"group.set_active", "作業中グループ", CommandMode::Instant, "group", "",
            SelectionPredicate::ZeroOrOneGroup, "グループは1つまで選べます。",
            "これから作るものが入るグループを決めます。", false,
            {"AT-UIX-006"}},
        {"workplane.set_active", "作業平面を使用", CommandMode::Instant, "workplane", "",
            SelectionPredicate::OneWorkPlane, "作業平面を1つ選んでください。",
            "選んだ作業平面を使います。", false,
            {"AT-WPL-003"}},
        {"draw.point", "作図点", CommandMode::Tool, "point", "D",
            SelectionPredicate::Always, "",
            "作図点を置きます。", true,
            {"AT-WIR-001", "AT-MEA-005"}},
        {"draw.line", "直線", CommandMode::Tool, "line", "L",
            SelectionPredicate::Always, "",
            "2点で直線を引きます。", true,
            {"AT-WIR-001", "AT-UIX-003"}},
        {"draw.polyline", "ポリライン", CommandMode::Tool, "polyline", "P",
            SelectionPredicate::Always, "",
            "点を続けて置きます。Backspaceで1点戻せます。", true,
            {"AT-WIR-002"}},
        {"draw.rectangle", "矩形", CommandMode::Tool, "rectangle", "R",
            SelectionPredicate::Always, "",
            "向かい合う2隅で四角を描きます。", true,
            {"AT-EXT-001"}},
        {"draw.circle", "円", CommandMode::Tool, "circle", "C",
            SelectionPredicate::Always, "",
            "中心と半径で円を描きます。", true,
            {"AT-WIR-001"}},
        {"draw.arc", "円弧", CommandMode::Tool, "arc", "A",
            SelectionPredicate::Always, "",
            "円弧を描きます。作り方は3通りから選べます。", true,
            {"AT-WIR-007"}},
        {"draw.bezier", "ベジェ", CommandMode::Tool, "bezier", "B",
            SelectionPredicate::Always, "",
            "制御点4つでベジェ曲線を描きます。", true,
            {"AT-WIR-001"}},
        {"draw.spline", "スプライン", CommandMode::Tool, "spline", "S",
            SelectionPredicate::Always, "",
            "通る点を並べてスプラインを描きます。", true,
            {"AT-WIR-001"}},
        {"wire.trim", "トリム", CommandMode::Tool, "trim", "X",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "境界まで切ります。残す側を選びます。", true,
            {"AT-WIR-006"}},
        {"wire.extend", "延長", CommandMode::Tool, "extend", "E",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "境界まで伸ばします。", true,
            {"AT-WIR-006"}},
        {"wire.split", "分割", CommandMode::Tool, "split", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "線を指定した場所で分けます。", true,
            {"AT-WIR-001"}},
        {"wire.move", "移動", CommandMode::Tool, "move", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を、2点で示した分だけ動かします。元の線は残しません。", true,
            {"AT-WIR-006"}},
        {"wire.copy", "コピー", CommandMode::Tool, "copy", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を、2点で示した分だけ離して複製します。元の線は残します。", true,
            {"AT-WIR-006"}},
        {"wire.mirror", "ミラー複製", CommandMode::Tool, "mirror", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "2点で引いた線を鏡にして複製します。元の線は残します。", true,
            {"AT-WIR-006"}},
        {"wire.rotate", "回転", CommandMode::Tool, "rotate", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "中心・始まりの向き・終わりの向きの3点で回します。", true,
            {"AT-WIR-006"}},
        {"wire.join", "結合", CommandMode::Tool, "join", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "2つの鎖を繋ぎます。隙間は明示して許します。", true,
            {"AT-WIR-004"}},
        {"wire.coincident", "端点一致", CommandMode::Tool, "coincident", "I",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "端点どうしを一致させます。", true,
            {"AT-WIR-006"}},
        {"wire.tangent", "接線接続", CommandMode::Tool, "tangent", "T",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "接線が続くように繋ぎます。", true,
            {"AT-WIR-006"}},
        {"wire.curvature", "曲率接続", CommandMode::Tool, "curvature", "Shift+T",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "曲率まで続くように繋ぎます。", true,
            {"AT-WIR-006"}},
        {"wire.chamfer", "C面取り", CommandMode::Tool, "chamfer", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "角を平らに落とします。", true,
            {"AT-WIR-006"}},
        {"wire.fillet", "R丸め", CommandMode::Tool, "fillet", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "角を丸くします。半径は数値で決めます。", true,
            {"AT-WIR-006"}},
        {"wire.offset", "オフセット", CommandMode::Instant, "offset", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を作業平面の中で「オフセット距離」ぶん平行に写します。元の線は残ります。", true,
            {"AT-WIR-006"}},
        {"wire.meet_lines", "2線を交点まで", CommandMode::Instant, "meet_lines", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "2本の直線を互いの交点まで延ばす(または縮める)。", true,
            {"AT-WIR-006"}},
        {"wire.intersection_points", "交点に点", CommandMode::Instant, "intersection_points", "",
            SelectionPredicate::TwoOrMoreWires, "ワイヤーを2つ以上選んでください。",
            "選んだ線どうしの交点すべてに作図点を作ります。線は変わりません。", true,
            {"AT-MEA-005"}},
        {"wire.corner_chamfer", "角の加工(落とす)", CommandMode::Instant, "corner_chamfer", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだポリラインの直線どうしの角を全部、「面取り量」で平らに落とします。", true,
            {"AT-WIR-006"}},
        {"wire.corner_fillet", "角の加工(丸める)", CommandMode::Instant, "corner_fillet", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだポリラインの直線どうしの角を全部、「丸め半径」の円弧にします。", true,
            {"AT-WIR-006"}},
        {"wire.set_datum", "基準線に設定", CommandMode::Instant, "set_datum", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を基準線にします(一点鎖線で出ます)。形は変わりません。", true,
            {"AT-DOC-005"}},
        {"wire.clear_datum", "基準解除", CommandMode::Instant, "clear_datum", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "基準線をやめて普通の線に戻します。形は変わりません。", true,
            {"AT-DOC-005"}},
        {"workplane.create", "作業平面を作る", CommandMode::Dialog, "workplane_new", "",
            SelectionPredicate::Always, "",
            "作業平面を作ります。作り方は12通りあります。", true,
            {"AT-WPL-001"}},
        {"grid.edit", "グリッド", CommandMode::Dialog, "grid", "",
            SelectionPredicate::Always, "",
            "グリッドの間隔と副点の数を決めます。", false,
            {"AT-UIX-005"}},
        {"grid.move_origin", "グリッド原点を移動", CommandMode::Tool, "grid_origin", "",
            SelectionPredicate::Always, "",
            "グリッドの原点を、作図点や幾何点へ合わせます。", false,
            {"AT-UIX-005"}},
        {"guide.create", "形状ガイド", CommandMode::Dialog, "guide", "G",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線から形状ガイドを作ります。作れない入力は理由を出して断ります。", true,
            {"AT-GEO-001", "AT-GEO-002", "AT-GEO-003", "AT-GEO-004", "AT-GEO-005", "AT-GEO-006", "AT-UIX-007"}},
        {"guide.revolve", "回転体", CommandMode::Instant, "guide_revolve", "",
            SelectionPredicate::TwoOrMoreWires, "断面の線と軸の直線を、この順に選んでください。",
            "1本目の線を、2本目の直線を軸に「回転体の角度」だけ回した断面を「回転体の断面の数」だけ"
            "並べ、その断面のロフトで形状ガイドを作ります(V1 の回転面と同じ近似)。", true,
            {"AT-GEO-003"}},
        {"guide.set_method", "面の作り方", CommandMode::Dialog, "guide_method", "",
            SelectionPredicate::Always, "",
            "面の作り方を7通りから選びます。使わない役割の行が残っていれば断ります。", false,
            {"AT-GEO-008"}},
        {"guide.add_row", "選択を表へ", CommandMode::Dialog, "guide_add", "",
            SelectionPredicate::OneOrMoreWiresOrGuideSurfaces,
            "ワイヤーか形状ガイドの面を1つ以上選んでください。",
            "選んだ線を役割表の新しい行にします。役割は作り方で使うものから選びます。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.append_row", "選択を既存行へ追加", CommandMode::Instant, "guide_append", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "選んだ線を、表で選んでいる行の端へつなぎます。逆向きの線は向きを直して足します。",
            false, {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_up", "行を上へ", CommandMode::Instant, "guide_up", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行を、同じ役割の中で1つ上へ動かします。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_down", "行を下へ", CommandMode::Instant, "guide_down", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行を、同じ役割の中で1つ下へ動かします。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_remove", "行を削除", CommandMode::Instant, "guide_remove", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行を消します。線そのものは消えません。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_reverse", "向きを反転", CommandMode::Instant, "guide_reverse", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行の向きを逆にします。線の並びも各線の向きも逆になります。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.build", "表から面を作る", CommandMode::Instant, "guide_build", "",
            SelectionPredicate::OneOrMoreGuideRows, "役割表に行を1つ以上入れてください。",
            "役割表のとおりに面を作ります。足りない役割があれば理由を出して断ります。", true,
            {"AT-GEO-008"}},
        {"guide.clear", "表を空にする", CommandMode::Instant, "guide_clear", "",
            SelectionPredicate::OneOrMoreGuideRows, "役割表に行を1つ以上入れてください。",
            "役割表の行を全部消します。作り方はそのままです。", false,
            {"AT-GEO-008"}},
        {"wire.project", "面へ投影", CommandMode::Tool, "project", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "線を作業平面や面へ投影します。", true,
            {"AT-FAB-007"}},
        {"wire.wrap_project", "回り込み投影", CommandMode::Instant, "wrap_project", "",
            SelectionPredicate::WiresAndTwoOrMoreGuideSurfaces,
            "ワイヤーを1つ以上と、落とす先の形状ガイドの面を2つ以上選んでください。",
            "角をまたぐ線を、面ごとの区間に分けて落とします(パノラミックウインドウなど)。"
            "面と面の間は橋渡ししません。落とす先が1枚なら「曲面へ投影」を使います。", true,
            {"AT-FAB-006"}},
        {"wire.project_surface", "曲面へ投影", CommandMode::Instant, "project_surface", "",
            SelectionPredicate::WiresAndOneGuideSurface,
            "ワイヤーを1つ以上と、落とす先の形状ガイドの面を1つ選んでください。",
            "線を、作業平面の向きに沿って形状ガイドの曲面へ落とします。曲がった面に窓を開ける元になります。",
            true, {"AT-FAB-013"}},
        {"part.extrude", "押し出し", CommandMode::Dialog, "extrude", "Shift+E",
            SelectionPredicate::OneOrMoreClosedProfiles, "閉じた輪郭を1つ以上選んでください。",
            "輪郭を押し出します。出来る体積と面の数を先に出します。", true,
            {"AT-EXT-001", "AT-EXT-002", "AT-EXT-003", "AT-EXT-004", "AT-EXT-005", "AT-EXT-006", "AT-EXT-007", "AT-EXT-008"}},
        {"part.thicken", "面に厚みを付ける", CommandMode::Dialog, "thicken", "",
            SelectionPredicate::OneOrMoreGuideSurfaces,
            "形状ガイドの面を1つ以上選んでください。",
            "選んだ面に厚みを付けて立体にします。厚みの付け方は外側・中央・内側から選びます。",
            true, {"AT-EXT-001"}},
        {"part.surface_jig", "治具を作る", CommandMode::Instant, "jig", "",
            SelectionPredicate::OneOrMoreGuideSurfaces,
            "形状ガイドの面を1つ以上選んでください。",
            "選んだ面に沿った当て板(治具)を作ります。「治具のすき間」だけ離した面に"
            "「治具の厚み」を付けます。厚みの符号で表側・裏側が決まります。", true,
            {"AT-EXT-001"}},
        {"part.thickness_placement", "厚みの付け方", CommandMode::Instant, "placement", "",
            SelectionPredicate::Always, "",
            "面に厚みを付けるときの付け方を、外側・中央・内側の順に切り替えます。", false,
            {"AT-EXT-001"}},
        {"part.thicken_to_plane", "面を平面まで立体に", CommandMode::Instant, "thicken_to", "",
            SelectionPredicate::OneGuideSurfaceAndOneWorkPlane,
            "形状ガイドの面を1つと、相手の作業平面を1つ選んでください。",
            "選んだ面と作業平面の間を埋めて立体にします。面が平面をまたいでいれば断ります。",
            true, {"AT-EXT-001"}},
        {"part.from_wire_cage", "ワイヤー群から部品", CommandMode::Dialog, "cage", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "閉じたワイヤーのかごから部品を作ります。", true,
            {"AT-GEO-010", "AT-GEO-011", "AT-GEO-012", "AT-GEO-013"}},
        {"part.boolean_add", "足す", CommandMode::Dialog, "boolean_add", "",
            SelectionPredicate::TwoParts, "部品を2つ選んでください。",
            "部品に足します。離ればなれになるなら断ります。", true,
            {"AT-EXT-007"}},
        {"part.boolean_cut", "引く", CommandMode::Dialog, "boolean_cut", "",
            SelectionPredicate::TwoParts, "部品を2つ選んでください。",
            "部品から引きます。分かれる場合は個数を先に知らせます。", true,
            {"AT-EXT-007"}},
        {"derived.freeze", "現在状態を固定", CommandMode::Instant, "freeze", "",
            SelectionPredicate::OneDerivedEntity, "派生したものを1つ選んでください。",
            "派生したものを固定して、独立した実体にします。", true,
            {"AT-DOC-004", "AT-FAB-014"}},
        {"fabrication.create", "製作モデルを作る", CommandMode::Dialog, "fab_new", "",
            SelectionPredicate::OnePartOrSurface, "部品か形状ガイドを1つ選んでください。",
            "部品から製作モデルを作ります。元の部品は変えません。", true,
            {"AT-FAB-001", "AT-FAB-002", "AT-FAB-003", "AT-FAB-004", "AT-FAB-005"}},
        {"fabrication.assign_role", "境界の役割", CommandMode::Instant, "fab_role", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を、いまの近似モデルの開口(閉じた輪)か折り線(開いた線)にします。", true,
            {"AT-FAB-006"}},
        {"fabrication.assign_relief_cut", "切れ目にする", CommandMode::Instant, "fab_relief", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ開いた線を、いまの近似モデルの切れ目にします(切るが部材は分かれない)。"
            "平らな部材の上の線だけ。閉じた線は開口にしてください。", true,
            {"AT-FAB-006"}},
        {"fabrication.preview_update", "プレビュー更新", CommandMode::Instant, "fab_update", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "元の部品の変更を製作モデルへ反映します。", true,
            {"AT-PER-001"}},
        {"fabrication.create_pattern", "型紙を作る", CommandMode::Dialog, "pattern", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "型紙を作ります。", true,
            {"AT-FAB-001"}},
        {"fabrication.set_assembly", "組立状態", CommandMode::Instant, "assembly", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "組み立ての途中の状態を決めます。", false,
            {"AT-FAB-009", "AT-FAB-010", "AT-FAB-011"}},
        {"fabrication.set_method", "近似の方式を切り替える", CommandMode::Instant,
            "fab_method", "", SelectionPredicate::Always, "",
            "次に作る近似モデルの方式を、帯へ近似し直す(V1方式)と、"
            "面を分類して展開する(V2方式)とで切り替えます。", false,
            {"AT-FAB-015"}},
        {"fabrication.freeze_output", "固定で作るもの", CommandMode::Instant,
            "freeze_output", "", SelectionPredicate::Always, "",
            "「現在状態を固定」で作るものを、ワイヤーのみ・部品のみ・両方の順に切り替えます。",
            false, {"AT-FAB-011"}},
        {"fabrication.set_connection_scope", "接続スコープ", CommandMode::Instant,
            "connection", "", SelectionPredicate::OneOrMoreWires,
            "ワイヤーを1つ以上選んでください。",
            "選んだ線を、近似の実形状へ寄せた「_接続」の線にします。元の線は変えません。",
            true, {"AT-FAB-015"}},
        {"fabrication.freeze_state", "現在状態を固定", CommandMode::Instant, "fab_freeze", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "いまの状態を固定して、独立したワイヤーや部品にします。", true,
            {"AT-FAB-011"}},
        {"export.validate", "出力を検査", CommandMode::Instant, "validate", "",
            SelectionPredicate::OnePart, "部品を1つ選んでください。",
            "書き出せる形かどうかを先に確かめます。", false,
            {"AT-EXP-011"}},
        {"export.stl", "STLで保存", CommandMode::Dialog, "stl", "",
            SelectionPredicate::OnePart, "部品を1つ選んでください。",
            "STLで書き出します。", false,
            {"AT-EXP-010"}},
        {"export.step", "STEPで保存", CommandMode::Dialog, "step", "",
            SelectionPredicate::OnePart, "部品を1つ選んでください。",
            "STEPで書き出します。", false,
            {"AT-EXP-010"}},
        {"export.svg", "SVGで保存", CommandMode::Dialog, "svg", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙をSVGで書き出します。", false,
            {"AT-EXP-012"}},
        {"export.dxf", "DXFで保存", CommandMode::Dialog, "dxf", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙をDXFで書き出します。", false,
            {"AT-EXP-012"}},
        // 紙に出して切るための道。台帳にはあったのに、押せる入口が無かった。
        {"export.pdf_1to1", "1:1 PDFで保存", CommandMode::Dialog, "pdf", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙を原寸(1:1)の PDF で書き出します。印刷して切るための紙です。", false,
            {"AT-EXP-013"}},
    };
    return table;
}

const CommandDescriptor* FindCommand(std::string_view id)
{
    const auto& table = CommandCatalog();
    const auto found = std::find_if(table.begin(), table.end(),
        [id](const CommandDescriptor& item) { return item.id == id; });
    return found == table.end() ? nullptr : &*found;
}

} // namespace kachakacha::v2::app
