#include "kachakacha/app/CommandCatalog.h"
#include <algorithm>
namespace kachakacha::v2::app {
std::string_view SelectionPredicateNameJa(SelectionPredicate value) noexcept
{
    switch (value) {
    case SelectionPredicate::Always: return "常に使えます。";
    case SelectionPredicate::HasDocument: return "文書がありません。";
    case SelectionPredicate::HasUndo: return "戻せる操作がありません。";
    case SelectionPredicate::HasRedo: return "やり直せる操作がありません。";
    case SelectionPredicate::HasVisibleGeometry: return "見えているものがありません。";
    case SelectionPredicate::OneWorkPlane: return "作業平面を1つ選んでください。";
    case SelectionPredicate::AnythingToFace:
        return "作業平面・立体の面・面・線のどれかを選んでください。";
    case SelectionPredicate::ZeroOrOneGroup: return "グループは1つまで選べます。";
    case SelectionPredicate::OneOrMoreWires: return "ワイヤーを1つ以上選んでください。";
    case SelectionPredicate::TwoOrMoreWires: return "ワイヤーを2つ以上選んでください。";
    case SelectionPredicate::TwoWireChains: return "鎖を2つ選んでください。";
    case SelectionPredicate::OneClosedProfile: return "閉じた輪郭を1つ選んでください。";
    case SelectionPredicate::ClosedProfilesOrSolidFace:
        return "閉じた輪郭を1つ以上、または立体の平らな面を選んでください。";
    case SelectionPredicate::OnePart: return "部品を1つ選んでください。";
    case SelectionPredicate::TwoOrMoreParts: return "部品を2つ以上選んでください(土台 1 つと相手 1 個以上)。";
    case SelectionPredicate::OneDerivedEntity: return "派生したものを1つ選んでください。";
    case SelectionPredicate::OneOrMoreDerivedEntities: return "派生したものを1つ以上選んでください。";
    case SelectionPredicate::OneFabricationModel: return "製作モデルを1つ選んでください。";
    case SelectionPredicate::OneFabricationPanel: return "部材を1つ選んでください。";
    case SelectionPredicate::OneOrMorePatterns: return "型紙を1つ以上選んでください。";
    case SelectionPredicate::OneOrMoreSelectedCurves: return "曲線を1つ以上選んでください。";
    case SelectionPredicate::OnePartOrSurface: return "部品か形状ガイドを1つ選んでください。";
    case SelectionPredicate::OneOrMoreParts: return "部品を1つ以上選んでください。";
    case SelectionPredicate::OneOrMorePartsOrSurfaces: return "部品か形状ガイドを1つ以上選んでください。";
    case SelectionPredicate::OneOrMoreGuideSurfaces: return "形状ガイドの面を1つ以上選んでください。";
    case SelectionPredicate::OneOrMoreWiresOrGuideSurfaces: return "ワイヤーか形状ガイドの面を1つ以上選んでください。";
    case SelectionPredicate::OneGuideRow: return "役割表の行を1つ選んでください。";
    case SelectionPredicate::OneOrMoreGuideRows: return "役割表に行を1つ以上入れてください。";
    case SelectionPredicate::WiresAndOneGuideSurface: return "ワイヤーを1つ以上と、落とす先の形状ガイドの面を1つ選んでください。";
    case SelectionPredicate::WiresAndTwoOrMoreGuideSurfaces: return "ワイヤーを1つ以上と、落とす先の形状ガイドの面を2つ以上選んでください。";
    case SelectionPredicate::OneGuideSurfaceAndOneWorkPlane: return "形状ガイドの面を1つと、相手の作業平面を1つ選んでください。";
    case SelectionPredicate::GuideSurfacesAndOneWorkPlane: return "形状ガイドの面を1つ以上と、相手の作業平面を1つ選んでください。";
    case SelectionPredicate::OneOrMoreHideable: return "線・部品・面のどれかを選んでください。";
    }
    return "";
}

const std::vector<CommandDescriptor>& CommandCatalog()
{
    // 並びは docs/v2/command-catalog.md と同じ順。決定的であること。
    static const std::vector<CommandDescriptor> table = {
        {"file.new", "新規", CommandMode::Instant, "new", "Ctrl+N",
            SelectionPredicate::HasDocument, "文書がありません。",
            "新しい文書を作ります。保存していない変更があれば先に確かめます。", true,
            {"AT-DOC-001"}},
        {"file.open", "開く", CommandMode::Dialog, "open", "Ctrl+O",
            SelectionPredicate::Always, "",
            "保存した文書を開きます。読めない中身なら、いまの文書はそのままにします。", true,
            {"AT-EXP-001", "AT-EXP-002", "AT-EXP-003"}},
        {"file.save", "保存", CommandMode::Instant, "save", "Ctrl+S",
            SelectionPredicate::HasDocument, "文書がありません。",
            "いまの文書を保存します。途中で失敗しても元のファイルは残ります。", false,
            {"AT-EXP-004"}},
        {"file.save_as", "名前を付けて保存", CommandMode::Dialog, "save_as", "Ctrl+Shift+S",
            SelectionPredicate::HasDocument, "文書がありません。",
            "名前を付けて保存します。", false,
            {"AT-EXP-004"}},
        {"edit.undo", "元に戻す", CommandMode::Instant, "undo", "Ctrl+Z",
            SelectionPredicate::HasUndo, "戻せる操作がありません。",
            "直前の操作を戻します。", true,
            {"AT-DOC-005"}},
        {"edit.redo", "やり直す", CommandMode::Instant, "redo", "Ctrl+Y",
            SelectionPredicate::HasRedo, "やり直せる操作がありません。",
            "戻した操作をやり直します。", true,
            {"AT-DOC-005"}},
        {"edit.delete", "削除", CommandMode::Instant, "delete", "Del",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだものを消します。下流があるものは、理由を出して断ります。", true,
            {"AT-DOC-005"}},
        {"view.hide_selected", "選択を隠す", CommandMode::Instant, "hide", "Ctrl+H",
            SelectionPredicate::OneOrMoreHideable, "線・部品・面のどれかを選んでください。",
            "選んだものを画面から隠します。形は消えません。", false,
            {"AT-UIX-010"}},
        {"view.show_all", "すべて表示", CommandMode::Instant, "show_all", "Ctrl+Shift+H",
            SelectionPredicate::HasDocument, "文書がありません。",
            "隠したものを全部出します。", false,
            {"AT-UIX-010"}},
        {"selection.activate", "選択", CommandMode::Tool, "select", "V",
            SelectionPredicate::Always, "",
            "選ぶ道具に戻ります。", false,
            {"AT-UIX-001"}},
        {"measure.open", "測定", CommandMode::Modeless, "measure", "M",
            SelectionPredicate::Always, "",
            "距離や角度を測ります。測った場所から作図点を作れます。", false,
            {"AT-MEA-001", "AT-MEA-002", "AT-MEA-003", "AT-MEA-004", "AT-MEA-005"}},
        {"edit.numeric", "数値で編集", CommandMode::Modeless, "edit_numeric", "",
            SelectionPredicate::Always, "",
            "選んだ作業平面(原点・法線・平面内X)や線(点・中心・軸・半径・角度)の数値を"
            "欄で直します。種類は変わりません。", false,
            {"AT-WIR-001", "AT-UIX-001"}},
        {"view.fit_all", "全体表示", CommandMode::Instant, "fit", "F",
            SelectionPredicate::HasVisibleGeometry, "見えているものがありません。",
            "見えているもの全部が入るように視点を合わせます。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.align_selection", "選択に正対", CommandMode::Instant, "align", "",
            SelectionPredicate::AnythingToFace,
            "作業平面・立体の面・面・線のどれかを選んでください。",
            "選んだものに正対します。向きだけでなく、真ん中と大きさも合わせます。"
            "形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.align_selection_back", "反対側から正対", CommandMode::Instant,
            "align_back", "",
            SelectionPredicate::AnythingToFace,
            "作業平面・立体の面・面・線のどれかを選んでください。",
            "選んだものの裏側から正対します。板の裏を見たいときに使います。"
            "形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.align_workplane", "正対", CommandMode::Instant, "align_workplane", "",
            SelectionPredicate::Always, "",
            "作業中の作図面に正対します(上の帯の「正対」)。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.display_settings", "表示設定", CommandMode::Dialog, "display", "",
            SelectionPredicate::Always, "",
            "線の太さや色などの見え方を変えます。形は変わりません。", false,
            {"AT-UIX-010"}},
        // 数の棚(板厚・許すずれ・型紙の余白・縮尺…)。製作モードの2枚目として常設していたが、
        // 右は「いまの道具の1枚」なので、表示設定と同じく自分の命令で前へ出す(指示書 C-09)。
        {"view.number_settings", "数の設定", CommandMode::Dialog, "numbers", "",
            SelectionPredicate::Always, "",
            "板厚・面取り量・型紙の余白・縮尺など、道具が共通で使う数を決めます。"
            "形はここでは変わりません。", false,
            {"AT-UIX-010"}},
        // 面の解析(プロンプト surface_analysis)。どのモードでも開ける。形は変わらない。
        {"view.surface_analysis", "面の解析", CommandMode::Dialog, "surface_analysis", "",
            SelectionPredicate::Always, "",
            "ゼブラ・平均曲率・ガウス曲率(可展性)・U/V 線・曲率コーム・境目の連続・入力線からのずれで"
            "面を塗ります。選んだ面(選んでいなければ全部の面)と、面を作る・面の編集の下見を塗ります。"
            "製作性の目安は数値の基準つきの診断材料です。形は変わりません。", false,
            {"AT-SRF-011"}},
        {"view.analysis_zebra", "ゼブラ", CommandMode::Instant, "zebra", "",
            SelectionPredicate::Always, "",
            "ゼブラ(反射の縞)を入れる・消すを切り替えます。棚は開かないので、面を作りながら"
            "下見の縞を見られます。形は変わりません。", false,
            {"AT-SRF-011"}},
        {"view.stage_all", "設計(すべて出す)", CommandMode::Instant, "stage_all", "Ctrl+1",
            SelectionPredicate::Always, "",
            "グリッドも補助線も出します(V1 の「設計」)。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_no_grid", "グリッドを消す", CommandMode::Instant, "stage_grid",
            "", SelectionPredicate::Always, "",
            "グリッドだけ消します。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_no_construction", "完成形(補助線も消す)", CommandMode::Instant,
            "stage_plain", "Ctrl+2", SelectionPredicate::Always, "",
            "グリッドも補助線も消して、出来上がりだけ見ます(V1 の「完成形」)。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"view.stage_selection_only", "選択だけ", CommandMode::Instant,
            "stage_selection", "Ctrl+3", SelectionPredicate::Always, "",
            "選んでいるものだけを出します(V1 の「選択だけ」)。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"entity.rename", "名前を変える", CommandMode::Instant, "rename", "F2",
            SelectionPredicate::Always, "",
            "一覧で選んでいるものの名前を変えます。形は変わりません。", false,
            {"AT-DOC-005"}},
        {"snap.toggle", "スナップ", CommandMode::Instant, "snap", "F3",
            SelectionPredicate::Always, "",
            "吸着を入り切りします。", false,
            {"AT-UIX-004"}},
        {"group.set_active", "作業中グループ", CommandMode::Instant, "group", "",
            SelectionPredicate::ZeroOrOneGroup, "グループは1つまで選べます。",
            "これから作るものが入るグループを決めます。", false,
            {"AT-UIX-006"}},
        {"group.create", "グループ化", CommandMode::Instant, "group_create", "Ctrl+G",
            SelectionPredicate::Always, "",
            "選んだものを1つのグループにします。何も選ばなければ空のグループを作ります。"
            "グループは整理のためだけのもので、形も依存も変わりません。", false,
            {"AT-UIX-006"}},
        {"group.dissolve", "グループを解く", CommandMode::Instant, "group_dissolve", "",
            SelectionPredicate::Always, "",
            "選んだグループを解きます。**中身は消えません。** 親のグループへ戻ります。",
            false, {"AT-UIX-006"}},
        {"group.rename", "グループの名前を変える", CommandMode::Instant, "group_rename",
            "", SelectionPredicate::Always, "",
            "選んだグループの名前を変えます。中身には触りません。", false,
            {"AT-UIX-006"}},
        {"workplane.set_active", "作業平面を使用", CommandMode::Instant, "workplane", "",
            SelectionPredicate::OneWorkPlane, "作業平面を1つ選んでください。",
            "選んだ作業平面を使います。", false,
            {"AT-WPL-003"}},
        {"draw.point", "作図点", CommandMode::Tool, "point", "D",
            SelectionPredicate::Always, "",
            "作図点を置きます。", true,
            {"AT-WIR-001", "AT-MEA-005"}},
        {"draw.line", "直線", CommandMode::Tool, "line", "L",
            SelectionPredicate::Always, "",
            "2点で直線を引きます。", true,
            {"AT-WIR-001", "AT-UIX-003"}},
        {"draw.polyline", "ポリライン", CommandMode::Tool, "polyline", "P",
            SelectionPredicate::Always, "",
            "点を続けて置きます。Backspaceで1点戻せます。", true,
            {"AT-WIR-002"}},
        {"draw.rectangle", "矩形", CommandMode::Tool, "rectangle", "R",
            SelectionPredicate::Always, "",
            "向かい合う2隅で四角を描きます。", true,
            {"AT-EXT-001"}},
        {"draw.circle", "円", CommandMode::Tool, "circle", "C",
            SelectionPredicate::Always, "",
            "中心と半径で円を描きます。", true,
            {"AT-WIR-001"}},
        {"draw.arc", "円弧", CommandMode::Tool, "arc", "A",
            SelectionPredicate::Always, "",
            "円弧を描きます。作り方は3通りから選べます。", true,
            {"AT-WIR-007"}},
        {"draw.bezier", "ベジェ", CommandMode::Tool, "bezier", "B",
            SelectionPredicate::Always, "",
            "制御点4つでベジェ曲線を描きます。", true,
            {"AT-WIR-001"}},
        {"draw.spline", "スプライン", CommandMode::Tool, "spline", "",
            SelectionPredicate::Always, "",
            "通る点を並べてスプラインを描きます。", true,
            {"AT-WIR-001"}},
        {"wire.trim", "トリム", CommandMode::Tool, "trim", "X",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "境界まで切ります。残す側を選びます。", true,
            {"AT-WIR-006"}},
        {"wire.extend", "延長", CommandMode::Tool, "extend", "E",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "境界まで伸ばします。", true,
            {"AT-WIR-006"}},
        {"wire.split", "分割", CommandMode::Tool, "split", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "線を指定した場所で分けます。", true,
            {"AT-WIR-001"}},
        {"wire.move", "移動", CommandMode::Tool, "move", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を、2点で示した分だけ動かします。元の線は残しません。", true,
            {"AT-WIR-006"}},
        {"wire.copy", "コピー", CommandMode::Tool, "copy", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を、2点で示した分だけ離して複製します。元の線は残します。", true,
            {"AT-WIR-006"}},
        {"wire.mirror", "ミラー複製", CommandMode::Tool, "mirror", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "2点で引いた線を鏡にして複製します。元の線は残します。", true,
            {"AT-WIR-006"}},
        {"wire.rotate", "回転", CommandMode::Tool, "rotate", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "中心・始まりの向き・終わりの向きの3点で回します。", true,
            {"AT-WIR-006"}},
        {"wire.join", "結合", CommandMode::Tool, "join", "",
            SelectionPredicate::TwoOrMoreWires, "つなぐ線を2つ以上選んでください。",
            "端でつながっている線を何本でも1本の並びにします(並べ替えと向きの反転はするが、"
            "形は変えない)。端が離れていれば断ります。", true,
            {"AT-WIR-004"}},
        {"wire.coincident", "端点一致", CommandMode::Tool, "coincident", "I",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "端点どうしを一致させます。", true,
            {"AT-WIR-006"}},
        {"wire.tangent", "接線接続", CommandMode::Tool, "tangent", "T",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "接線が続くように繋ぎます。", true,
            {"AT-WIR-006"}},
        {"wire.curvature", "曲率接続", CommandMode::Tool, "curvature", "Shift+T",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "曲率まで続くように繋ぎます。", true,
            {"AT-WIR-006"}},
        {"wire.chamfer", "C面取り", CommandMode::Tool, "chamfer", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "角を平らに落とします。", true,
            {"AT-WIR-006"}},
        {"wire.fillet", "R丸め", CommandMode::Tool, "fillet", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "角を丸くします。半径は数値で決めます。", true,
            {"AT-WIR-006"}},
        {"wire.offset", "オフセット", CommandMode::Instant, "offset", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を作業平面の中で「オフセット距離」ぶん平行に写します。元の線は残ります。", true,
            {"AT-WIR-006"}},
        {"wire.meet_lines", "2線を交点まで", CommandMode::Instant, "meet_lines", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "2本の直線を互いの交点まで延ばす(または縮める)。", true,
            {"AT-WIR-006"}},
        {"wire.intersection_points", "交点に点", CommandMode::Instant, "intersection_points", "",
            SelectionPredicate::TwoOrMoreWires, "ワイヤーを2つ以上選んでください。",
            "選んだ線どうしの交点すべてに作図点を作ります。線は変わりません。", true,
            {"AT-MEA-005"}},
        // 形から点を作る(PRD-072)。core(app/PointSources)は書けていたのに、
        // 画面から呼ぶ道が無かった。車輪の中心も窓の中心も、座標を目で読んで
        // 手で打ち直すしかなかった。
        // 不具合を見つけた瞬間の状態を短い文にして持ち出す。
        // 何が起きたかを言葉で説明し直すのは難しく、たいてい抜ける。
        {"help.copy_diagnostics", "診断情報をコピー", CommandMode::Instant,
            "copy_diagnostics", "", SelectionPredicate::Always, "",
            "いまの道具・右の棚・カーソル・吸着・選択を短い文にして貼り板へ入れます。"
            "文書の中身や置き場所は入りません。", false,
            {"AT-UIX-011"}},
        {"wire.center_points", "中心に点", CommandMode::Instant, "center_points", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ円・円弧の中心に作図点を作ります。線は変わりません。", true,
            {"AT-MEA-005"}},
        {"wire.key_points", "端点と中点に点", CommandMode::Instant, "key_points", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線の始点・終点・中点に作図点を作ります。線は変わりません。", true,
            {"AT-MEA-005"}},
        {"wire.corner_chamfer", "角の加工(落とす)", CommandMode::Instant, "corner_chamfer", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだポリラインの直線どうしの角を全部、「面取り量」で平らに落とします。", true,
            {"AT-WIR-006"}},
        {"wire.corner_fillet", "角の加工(丸める)", CommandMode::Instant, "corner_fillet", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだポリラインの直線どうしの角を全部、「丸め半径」の円弧にします。", true,
            {"AT-WIR-006"}},
        // 配列。窓を10個並べるのに、1つずつ複製して位置を打つのは間違いのもと。
        {"wire.array_linear", "直線に並べる", CommandMode::Dialog, "array_line", "",
            SelectionPredicate::OneOrMoreWires, "並べる線を1つ以上選んでください。",
            "選んだ線を、等間隔に並べて写します。元の線は残ります。", false,
            {"AT-WIR-006"}},
        {"wire.array_circular", "円に並べる", CommandMode::Dialog, "array_circle", "",
            SelectionPredicate::OneOrMoreWires, "並べる線を1つ以上選んでください。",
            "選んだ線を、中心のまわりに等角で並べて写します。軸は作図面の法線です。",
            false, {"AT-WIR-006"}},
        {"wire.set_datum", "基準線に設定", CommandMode::Instant, "set_datum", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を基準線にします(一点鎖線で出ます)。形は変わりません。", true,
            {"AT-DOC-005"}},
        {"wire.clear_datum", "基準解除", CommandMode::Instant, "clear_datum", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "基準線をやめて普通の線に戻します。形は変わりません。", true,
            {"AT-DOC-005"}},
        {"workplane.create", "作業平面を作る", CommandMode::Dialog, "workplane_new", "",
            SelectionPredicate::Always, "",
            "作業平面を作ります。作り方は12通りあります。", true,
            {"AT-WPL-001"}},
        {"grid.edit", "グリッド", CommandMode::Dialog, "grid", "",
            SelectionPredicate::Always, "",
            "グリッドの間隔と副点の数を決めます。", false,
            {"AT-UIX-005"}},
        {"grid.move_origin", "グリッド原点を移動", CommandMode::Tool, "grid_origin", "",
            SelectionPredicate::Always, "",
            "グリッドの原点を、作図点や幾何点へ合わせます。", false,
            {"AT-UIX-005"}},
        // **人が使う入口はこれ1つ**(オーナー指示 2026-09-15 §10)。
        // 「形状ガイド」と役割表の2本立ては、人から見て別物に見えていた。
        // 中では今までの GuideTable をそのまま使う。
        {"surface.create", "面を作る", CommandMode::Dialog, "surface", "G",
            SelectionPredicate::OneOrMoreWiresOrGuideSurfaces,
            "線を1つ以上、または形状ガイドの面を選んでください。",
            "選んだものから面を作ります。作り方は選択内容から薦めますが、"
            "右の棚でいつでも変えられます。方式を変えても入れたものは消えません。",
            true, {"AT-GEO-001", "AT-GEO-002", "AT-GEO-003", "AT-GEO-008", "AT-UIX-007"}},
        {"guide.revolve", "回転体", CommandMode::Instant, "guide_revolve", "",
            SelectionPredicate::TwoOrMoreWires,
            "断面の線(何本でも)と、最後に軸の直線を選んでください。",
            "最後に選んだ直線を軸に、ほかの線(断面。何本でも)を「回転体の角度」だけ回した"
            "形状ガイドを作ります(断面 1 本ごとに 1 枚。核が断面そのものを回します)。", true,
            {"AT-GEO-003"}},
        // 面の編集(プロンプト additional_surface_tools)。どれも道具から始め、3D で面や縁を
        // 押して入れる。元の面は残し、新しい面(U/V 線は線)を作る。
        {"surface.match", "面を合わせる", CommandMode::Dialog, "surface_match", "",
            SelectionPredicate::Always, "",
            "直す面の縁を、隣の面の縁へ G0/G1/G2 で合わせます。縁は面の縁の近くを押して選びます。"
            "元の面は残し、合わせた新しい面を作ります。滑らかさは作ったあとで測ります。",
            true, {"AT-SRF-005"}},
        {"surface.bridge", "面をつなぐ", CommandMode::Dialog, "surface_bridge", "",
            SelectionPredicate::Always, "",
            "2 枚の面の縁のあいだを渡す面を作ります。両端の滑らかさ(G0/G1/G2)と張りの強さを選べます。",
            true, {"AT-SRF-006"}},
        {"surface.refit", "面を整える", CommandMode::Dialog, "surface_refit", "",
            SelectionPredicate::Always, "",
            "形を許容の内側に保ったまま、制御点の少ない面に作り直します。前後の最大のずれと"
            "制御点の数を出します。許容に届かない・減らないときは作りません。",
            true, {"AT-SRF-007"}},
        {"surface.mirror", "対称に写す", CommandMode::Dialog, "surface_mirror", "",
            SelectionPredicate::Always, "",
            "面を対称面(車体の中心など)に写し、境目で面が折れていないかを測ります。何枚でも写せます。",
            true, {"AT-SRF-008"}},
        {"surface.iso_curves", "U/V 線を取り出す", CommandMode::Dialog, "surface_iso", "",
            SelectionPredicate::Always, "",
            "面の U 方向・V 方向の線を、ふつうの線として取り出します。分割線や特徴線の元にできます。",
            true, {"AT-SRF-009"}},
        {"guide.set_method", "面の作り方", CommandMode::Dialog, "guide_method", "",
            SelectionPredicate::Always, "",
            "面の作り方を7通りから選びます。使わない役割の行が残っていれば断ります。", false,
            {"AT-GEO-008"}},
        {"guide.add_row", "選択を表へ", CommandMode::Dialog, "guide_add", "",
            SelectionPredicate::OneOrMoreWiresOrGuideSurfaces,
            "ワイヤーか形状ガイドの面を1つ以上選んでください。",
            "選んだ線を役割表の新しい行にします。役割は作り方で使うものから選びます。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.append_row", "選択を既存行へ追加", CommandMode::Instant, "guide_append", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "選んだ線を、表で選んでいる行の端へつなぎます。逆向きの線は向きを直して足します。",
            false, {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_up", "行を上へ", CommandMode::Instant, "guide_up", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行を、同じ役割の中で1つ上へ動かします。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_down", "行を下へ", CommandMode::Instant, "guide_down", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行を、同じ役割の中で1つ下へ動かします。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_remove", "行を削除", CommandMode::Instant, "guide_remove", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行を消します。線そのものは消えません。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.row_reverse", "向きを反転", CommandMode::Instant, "guide_reverse", "",
            SelectionPredicate::OneGuideRow, "役割表の行を1つ選んでください。",
            "表で選んでいる行の向きを逆にします。線の並びも各線の向きも逆になります。", false,
            {"AT-GEO-008", "AT-UIX-007"}},
        {"guide.build", "表から面を作る", CommandMode::Instant, "guide_build", "",
            SelectionPredicate::OneOrMoreGuideRows, "役割表に行を1つ以上入れてください。",
            "役割表のとおりに面を作ります。足りない役割があれば理由を出して断ります。", true,
            {"AT-GEO-008"}},
        {"guide.clear", "表を空にする", CommandMode::Instant, "guide_clear", "",
            SelectionPredicate::OneOrMoreGuideRows, "役割表に行を1つ以上入れてください。",
            "役割表の行を全部消します。作り方はそのままです。", false,
            {"AT-GEO-008"}},
        {"wire.project", "面へ投影", CommandMode::Tool, "project", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "線を作業平面や面へ投影します。", true,
            {"AT-FAB-007"}},
        {"wire.wrap_project", "回り込み投影", CommandMode::Instant, "wrap_project", "",
            SelectionPredicate::WiresAndTwoOrMoreGuideSurfaces,
            "ワイヤーを1つ以上と、落とす先の形状ガイドの面を2つ以上選んでください。",
            "角をまたぐ線を、面ごとの区間に分けて落とします(パノラミックウインドウなど)。"
            "面と面の間は橋渡ししません。落とす先が1枚なら「曲面へ投影」を使います。", true,
            {"AT-FAB-006"}},
        {"wire.project_surface", "曲面へ投影", CommandMode::Instant, "project_surface", "",
            SelectionPredicate::WiresAndOneGuideSurface,
            "ワイヤーを1つ以上と、落とす先の形状ガイドの面を1つ選んでください。",
            "線を、作業平面の向きに沿って形状ガイドの曲面へ落とします。落ちた線は面の上の曲線で、"
            "折れ線にしません(面の形が無いときだけ標本から折れ線で落とします)。曲がった面に窓を開ける元になります。",
            true, {"AT-FAB-013", "AT-SRF-010"}},
        {"part.extrude", "押し出し", CommandMode::Dialog, "extrude", "Shift+E",
            SelectionPredicate::ClosedProfilesOrSolidFace,
            "閉じた輪郭を1つ以上、または立体の平らな面を選んでください。",
            "輪郭を押し出します。立体の平らな面を選べば、その面をつまんで押し引きできます。"
            "出来る体積と面の数を先に出します。", true,
            {"AT-EXT-001", "AT-EXT-002", "AT-EXT-003", "AT-EXT-004", "AT-EXT-005", "AT-EXT-006", "AT-EXT-007", "AT-EXT-008"}},
        {"part.thicken", "面に厚みを付ける", CommandMode::Dialog, "thicken", "",
            SelectionPredicate::OneOrMoreGuideSurfaces,
            "形状ガイドの面を1つ以上選んでください。",
            "道具から始められます。押した時点で何も選んでいなくても棚が構え、"
            "3Dで形状ガイドの面を押すと入ります(押し直すと外れます)。"
            "作り方は外側・中央・内側・平面まで(相手の作業平面)から選びます。",
            true, {"AT-EXT-001"}},
        {"part.surface_jig", "治具を作る", CommandMode::Instant, "jig", "",
            SelectionPredicate::OneOrMoreGuideSurfaces,
            "形状ガイドの面を1つ以上選んでください。",
            "選んだ面に沿った当て板(治具)を作ります。「治具のすき間」だけ離した面に"
            "「治具の厚み」を付けます。厚みの符号で表側・裏側が決まります。", true,
            {"AT-EXT-001"}},
        {"part.thickness_placement", "厚みの付け方", CommandMode::Instant, "placement", "",
            SelectionPredicate::Always, "",
            "面に厚みを付けるときの付け方を、外側・中央・内側の順に切り替えます。", false,
            {"AT-EXT-001"}},
        {"part.thicken_to_plane", "面を平面まで立体に", CommandMode::Instant, "thicken_to", "",
            SelectionPredicate::GuideSurfacesAndOneWorkPlane,
            "形状ガイドの面を1つ以上と、相手の作業平面を1つ選んでください。",
            "選んだ面と作業平面の間を埋めて立体にします(面ごとに 1 部品、1 回で戻る)。"
            "面が平面をまたいでいれば断ります。",
            true, {"AT-EXT-001"}},
        {"part.from_wire_cage", "ワイヤー群から部品", CommandMode::Dialog, "cage", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "閉じたワイヤーのかごから部品を作ります。", true,
            {"AT-GEO-010", "AT-GEO-011", "AT-GEO-012", "AT-GEO-013"}},
        {"part.boolean_add", "足す", CommandMode::Dialog, "boolean_add", "",
            SelectionPredicate::TwoOrMoreParts, "部品を2つ以上選んでください(土台 1 つと相手 1 個以上)。",
            "部品に足します。離ればなれになるなら断ります。", true,
            {"AT-EXT-007"}},
        {"part.boolean_cut", "引く", CommandMode::Dialog, "boolean_cut", "",
            SelectionPredicate::TwoOrMoreParts, "部品を2つ以上選んでください(土台 1 つと相手 1 個以上)。",
            "部品から引きます。分かれる場合は個数を先に知らせます。", true,
            {"AT-EXT-007"}},
        {"part.boolean_intersect", "交差", CommandMode::Dialog, "boolean_intersect", "",
            SelectionPredicate::TwoOrMoreParts, "部品を2つ以上選んでください(土台 1 つと相手 1 個以上)。",
            "土台と相手に共通する部分だけを残します(相手が何個でも、全部に共通する部分)。"
            "重ならなければ断ります。", true,
            {"AT-EXT-007"}},
        {"derived.freeze", "現在状態を固定", CommandMode::Instant, "freeze", "",
            SelectionPredicate::OneOrMoreDerivedEntities, "派生したものを1つ以上選んでください。",
            "派生したものを固定して、独立した実体にします(選んだものごとに 1 つ。1 回で戻る)。", true,
            {"AT-DOC-004", "AT-FAB-014"}},
        {"fabrication.create", "製作モデルを作る", CommandMode::Dialog, "fab_new", "",
            SelectionPredicate::OneOrMorePartsOrSurfaces,
            "部品か形状ガイドを1つ以上選んでください(何個でも 1 つの製作モデルにまとめます)。",
            "部品や形状ガイドから製作モデルを作ります(元は何個でも)。元の部品は変えません。", true,
            {"AT-FAB-001", "AT-FAB-002", "AT-FAB-003", "AT-FAB-004", "AT-FAB-005"}},
        {"fabrication.assign_role", "境界の役割", CommandMode::Instant, "fab_role", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線を、いまの近似モデルの開口(閉じた輪)か折り線(開いた線)にします。", true,
            {"AT-FAB-006"}},
        {"fabrication.assign_relief_cut", "切れ目にする", CommandMode::Instant, "fab_relief", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ開いた線を、いまの近似モデルの切れ目にします(切るが部材は分かれない)。"
            "平らな部材の上の線だけ。閉じた線は開口にしてください。", true,
            {"AT-FAB-006"}},
        {"fabrication.preview_update", "プレビュー更新", CommandMode::Instant, "fab_update", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "元の部品の変更を製作モデルへ反映します。", true,
            {"AT-PER-001"}},
        {"fabrication.create_pattern", "型紙を作る", CommandMode::Dialog, "pattern", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "型紙を作ります。", true,
            {"AT-FAB-001"}},
        {"fabrication.set_assembly", "組立状態", CommandMode::Instant, "assembly", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "組み立ての途中の状態を決めます。", false,
            {"AT-FAB-009", "AT-FAB-010", "AT-FAB-011"}},
        {"fabrication.set_method", "近似の方式を切り替える", CommandMode::Instant,
            "fab_method", "", SelectionPredicate::Always, "",
            "次に作る近似モデルの方式を、帯へ近似し直す(V1方式)と、"
            "面を分類して展開する(V2方式)とで切り替えます。", false,
            {"AT-FAB-015"}},
        {"fabrication.freeze_output", "固定で作るもの", CommandMode::Instant,
            "freeze_output", "", SelectionPredicate::Always, "",
            "「現在状態を固定」で作るものを、ワイヤーのみ・部品のみ・両方の順に切り替えます。",
            false, {"AT-FAB-011"}},
        {"fabrication.set_connection_scope", "接続スコープ", CommandMode::Instant,
            "connection", "", SelectionPredicate::OneOrMoreWires,
            "ワイヤーを1つ以上選んでください。",
            "選んだ線を、近似の実形状へ寄せた「_接続」の線にします。元の線は変えません。",
            true, {"AT-FAB-015"}},
        {"fabrication.freeze_state", "現在状態を固定", CommandMode::Instant, "fab_freeze", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "いまの状態を固定して、独立したワイヤーや部品にします。", true,
            {"AT-FAB-011"}},
        {"fabrication.freeze_flat", "展開状態(0%)を線にする", CommandMode::Instant, "fab_flat", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "いまの曲げ具合を変えずに、0%(平らに展開した状態)の輪郭を線として作ります。"
            "近似モデルはそのまま残ります。", true,
            {"AT-FAB-011"}},
        {"fabrication.freeze_target", "目標形状(100%)を固定", CommandMode::Instant, "fab_target",
            "", SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "いまの曲げ具合を変えずに、100%(目標の形)の状態を固定して、"
            "固定で作るものの設定どおりに線や部品にします。近似モデルはそのまま残ります。", true,
            {"AT-FAB-011"}},
        {"fabrication.freeze_wires", "輪郭を線にする", CommandMode::Instant, "fab_wires", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "いまの曲げ状態の輪郭だけを線として作ります(固定で作るものの設定に関わらず"
            "線のみ)。近似モデルはそのまま残ります。", true,
            {"AT-FAB-011"}},
        {"fabrication.edit_part", "近似部品の編集", CommandMode::Modeless, "fab_edit", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "近似モデルの部材の編集(分割・結合・切れ目・半径 AUTO/LOCK・曲げ状態)の棚を出します。"
            "文書はここでは変えません。", false, {"AT-FAB-005"}},
        {"fabrication.merge_parts", "部材を1つにする", CommandMode::Instant,
            "fab_merge", "", SelectionPredicate::OneFabricationModel,
            "製作モデルを1つ選んでください。",
            "隣り合う2つの部材を1つにします。接着線が1本減ります。"
            "**1度目は前と後を見せるだけで、文書は変えません。**"
            "もう一度同じ指示を出すと、その形にします。"
            "やめるときは Esc か道具を替えてください。", true,
            {"AT-FAB-005"}},
        {"fabrication.split_part", "部材を分ける", CommandMode::Instant, "fab_split", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "1つの部材を2つに分けます。ずれは減りますが、貼り合わせが増えます。"
            "**1度目は前と後を見せるだけで、文書は変えません。**"
            "もう一度同じ指示を出すと、その形にします。"
            "やめるときは Esc か道具を替えてください。", true,
            {"AT-FAB-005"}},
        {"fabrication.set_unfold_base", "展開の基準にする辺", CommandMode::Instant,
            "fab_unfold_base", "", SelectionPredicate::OneFabricationModel,
            "製作モデルを1つ選んでください。",
            "展開したときに動かさない辺を決めます。棚の「曲げる部材」に書いた番号の"
            "手前の境目が基準になります。床板の縁を基準にすれば、展開しても"
            "床板はその場に残り、まわりの板だけが開きます。", true,
            {"AT-FAB-011"}},
        {"export.validate", "出力を検査", CommandMode::Instant, "validate", "",
            SelectionPredicate::OneOrMoreParts, "部品を1つ以上選んでください。",
            "書き出せる形かどうかを先に確かめます(選んだ部品を全部)。", false,
            {"AT-EXP-011"}},
        {"export.stl", "STLで保存", CommandMode::Dialog, "stl", "",
            SelectionPredicate::OneOrMoreParts, "部品を1つ以上選んでください。",
            "STLで書き出します(選んだ部品を全部 1 つのファイルへ)。", false,
            {"AT-EXP-010"}},
        {"export.step", "STEPで保存", CommandMode::Dialog, "step", "",
            SelectionPredicate::OneOrMoreParts, "部品を1つ以上選んでください。",
            "STEPで書き出します(選んだ部品を全部 1 つのファイルへ)。", false,
            {"AT-EXP-010"}},
        {"export.svg", "SVGで保存", CommandMode::Dialog, "svg", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙をSVGで書き出します。", false,
            {"AT-EXP-012"}},
        {"export.dxf", "DXFで保存", CommandMode::Dialog, "dxf", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙をDXFで書き出します。", false,
            {"AT-EXP-012"}},
        // 紙に出して切るための道。台帳にはあったのに、押せる入口が無かった。
        {"export.pdf_1to1", "1:1 PDFで保存", CommandMode::Dialog, "pdf", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙を原寸(1:1)の PDF で書き出します。印刷して切るための紙です。", false,
            {"AT-EXP-013"}},
    };
    return table;
}

const CommandDescriptor* FindCommand(std::string_view id)
{
    const auto& table = CommandCatalog();
    const auto found = std::find_if(table.begin(), table.end(),
        [id](const CommandDescriptor& item) { return item.id == id; });
    return found == table.end() ? nullptr : &*found;
}

} // namespace kachakacha::v2::app
