#include "kachakacha/app/CommandCatalog.h"
#include <algorithm>
namespace kachakacha::v2::app {
std::string_view SelectionPredicateNameJa(SelectionPredicate value) noexcept
{
    switch (value) {
    case SelectionPredicate::Always: return "常に使えます。";
    case SelectionPredicate::HasDocument: return "文書がありません。";
    case SelectionPredicate::HasUndo: return "戻せる操作がありません。";
    case SelectionPredicate::HasRedo: return "やり直せる操作がありません。";
    case SelectionPredicate::HasVisibleGeometry: return "見えているものがありません。";
    case SelectionPredicate::OneWorkPlane: return "作業平面を1つ選んでください。";
    case SelectionPredicate::OnePlanarFaceOrWorkPlane: return "平らな面か作業平面を1つ選んでください。";
    case SelectionPredicate::ZeroOrOneGroup: return "グループは1つまで選べます。";
    case SelectionPredicate::OneOrMoreWires: return "ワイヤーを1つ以上選んでください。";
    case SelectionPredicate::TwoWireChains: return "鎖を2つ選んでください。";
    case SelectionPredicate::OneClosedProfile: return "閉じた輪郭を1つ選んでください。";
    case SelectionPredicate::OneOrMoreClosedProfiles: return "閉じた輪郭を1つ以上選んでください。";
    case SelectionPredicate::OnePart: return "部品を1つ選んでください。";
    case SelectionPredicate::TwoParts: return "部品を2つ選んでください。";
    case SelectionPredicate::OneDerivedEntity: return "派生したものを1つ選んでください。";
    case SelectionPredicate::OneFabricationModel: return "製作モデルを1つ選んでください。";
    case SelectionPredicate::OneFabricationPanel: return "部材を1つ選んでください。";
    case SelectionPredicate::OneOrMorePatterns: return "型紙を1つ以上選んでください。";
    case SelectionPredicate::OneOrMoreSelectedCurves: return "曲線を1つ以上選んでください。";
    case SelectionPredicate::OnePartOrSurface: return "部品か形状ガイドを1つ選んでください。";
    }
    return "";
}

const std::vector<CommandDescriptor>& CommandCatalog()
{
    // 並びは docs/v2/command-catalog.md と同じ順。決定的であること。
    static const std::vector<CommandDescriptor> table = {
        {"file.new", "新規", CommandMode::Instant, "new", "Ctrl+N",
            SelectionPredicate::HasDocument, "文書がありません。",
            "新しい文書を作ります。保存していない変更があれば先に確かめます。", true,
            {"AT-DOC-001"}},
        {"file.open", "開く", CommandMode::Dialog, "open", "Ctrl+O",
            SelectionPredicate::Always, "",
            "保存した文書を開きます。読めない中身なら、いまの文書はそのままにします。", true,
            {"AT-EXP-001", "AT-EXP-002", "AT-EXP-003"}},
        {"file.save", "保存", CommandMode::Instant, "save", "Ctrl+S",
            SelectionPredicate::HasDocument, "文書がありません。",
            "いまの文書を保存します。途中で失敗しても元のファイルは残ります。", false,
            {"AT-EXP-004"}},
        {"file.save_as", "名前を付けて保存", CommandMode::Dialog, "save_as", "Ctrl+Shift+S",
            SelectionPredicate::HasDocument, "文書がありません。",
            "名前を付けて保存します。", false,
            {"AT-EXP-004"}},
        {"edit.undo", "元に戻す", CommandMode::Instant, "undo", "Ctrl+Z",
            SelectionPredicate::HasUndo, "戻せる操作がありません。",
            "直前の操作を戻します。", true,
            {"AT-DOC-005"}},
        {"edit.redo", "やり直す", CommandMode::Instant, "redo", "Ctrl+Y",
            SelectionPredicate::HasRedo, "やり直せる操作がありません。",
            "戻した操作をやり直します。", true,
            {"AT-DOC-005"}},
        {"selection.activate", "選択", CommandMode::Tool, "select", "Esc",
            SelectionPredicate::Always, "",
            "選ぶ道具に戻ります。", false,
            {"AT-UIX-001"}},
        {"measure.open", "測定", CommandMode::Modeless, "measure", "M",
            SelectionPredicate::Always, "",
            "距離や角度を測ります。測った場所から作図点を作れます。", false,
            {"AT-MEA-001", "AT-MEA-002", "AT-MEA-003", "AT-MEA-004", "AT-MEA-005"}},
        {"view.fit_all", "全体表示", CommandMode::Instant, "fit", "F",
            SelectionPredicate::HasVisibleGeometry, "見えているものがありません。",
            "見えているもの全部が入るように視点を合わせます。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.align_selection", "選択に正対", CommandMode::Instant, "align", "",
            SelectionPredicate::OnePlanarFaceOrWorkPlane, "平らな面か作業平面を1つ選んでください。",
            "選んだ平面に正対します。形は変わりません。", false,
            {"AT-UIX-008"}},
        {"view.display_settings", "表示設定", CommandMode::Dialog, "display", "",
            SelectionPredicate::Always, "",
            "線の太さや色などの見え方を変えます。形は変わりません。", false,
            {"AT-UIX-010"}},
        {"snap.toggle", "スナップ", CommandMode::Instant, "snap", "S",
            SelectionPredicate::Always, "",
            "吸着を入り切りします。", false,
            {"AT-UIX-004"}},
        {"group.set_active", "作業中グループ", CommandMode::Instant, "group", "",
            SelectionPredicate::ZeroOrOneGroup, "グループは1つまで選べます。",
            "これから作るものが入るグループを決めます。", false,
            {"AT-UIX-006"}},
        {"workplane.set_active", "作業平面を使用", CommandMode::Instant, "workplane", "",
            SelectionPredicate::OneWorkPlane, "作業平面を1つ選んでください。",
            "選んだ作業平面を使います。", false,
            {"AT-WPL-003"}},
        {"draw.point", "作図点", CommandMode::Tool, "point", "",
            SelectionPredicate::Always, "",
            "作図点を置きます。", true,
            {"AT-WIR-001", "AT-MEA-005"}},
        {"draw.line", "直線", CommandMode::Tool, "line", "L",
            SelectionPredicate::Always, "",
            "2点で直線を引きます。", true,
            {"AT-WIR-001", "AT-UIX-003"}},
        {"draw.polyline", "ポリライン", CommandMode::Tool, "polyline", "P",
            SelectionPredicate::Always, "",
            "点を続けて置きます。Backspaceで1点戻せます。", true,
            {"AT-WIR-002"}},
        {"draw.rectangle", "矩形", CommandMode::Tool, "rectangle", "R",
            SelectionPredicate::Always, "",
            "向かい合う2隅で四角を描きます。", true,
            {"AT-EXT-001"}},
        {"draw.circle", "円", CommandMode::Tool, "circle", "C",
            SelectionPredicate::Always, "",
            "中心と半径で円を描きます。", true,
            {"AT-WIR-001"}},
        {"draw.arc", "円弧", CommandMode::Tool, "arc", "A",
            SelectionPredicate::Always, "",
            "円弧を描きます。作り方は3通りから選べます。", true,
            {"AT-WIR-007"}},
        {"draw.bezier", "ベジェ", CommandMode::Tool, "bezier", "",
            SelectionPredicate::Always, "",
            "制御点4つでベジェ曲線を描きます。", true,
            {"AT-WIR-001"}},
        {"draw.spline", "スプライン", CommandMode::Tool, "spline", "",
            SelectionPredicate::Always, "",
            "通る点を並べてスプラインを描きます。", true,
            {"AT-WIR-001"}},
        {"wire.trim", "トリム", CommandMode::Tool, "trim", "T",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "境界まで切ります。残す側を選びます。", true,
            {"AT-WIR-006"}},
        {"wire.extend", "延長", CommandMode::Tool, "extend", "E",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "境界まで伸ばします。", true,
            {"AT-WIR-006"}},
        {"wire.split", "分割", CommandMode::Tool, "split", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "線を指定した場所で分けます。", true,
            {"AT-WIR-001"}},
        {"wire.join", "結合", CommandMode::Tool, "join", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "2つの鎖を繋ぎます。隙間は明示して許します。", true,
            {"AT-WIR-004"}},
        {"wire.coincident", "端点一致", CommandMode::Tool, "coincident", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "端点どうしを一致させます。", true,
            {"AT-WIR-006"}},
        {"wire.tangent", "接線接続", CommandMode::Tool, "tangent", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "接線が続くように繋ぎます。", true,
            {"AT-WIR-006"}},
        {"wire.curvature", "曲率接続", CommandMode::Tool, "curvature", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "曲率まで続くように繋ぎます。", true,
            {"AT-WIR-006"}},
        {"wire.chamfer", "C面取り", CommandMode::Tool, "chamfer", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "角を平らに落とします。", true,
            {"AT-WIR-006"}},
        {"wire.fillet", "R丸め", CommandMode::Tool, "fillet", "",
            SelectionPredicate::TwoWireChains, "鎖を2つ選んでください。",
            "角を丸くします。半径は数値で決めます。", true,
            {"AT-WIR-006"}},
        {"workplane.create", "作業平面を作る", CommandMode::Dialog, "workplane_new", "",
            SelectionPredicate::Always, "",
            "作業平面を作ります。作り方は11通りあります。", true,
            {"AT-WPL-001"}},
        {"grid.edit", "グリッド", CommandMode::Dialog, "grid", "",
            SelectionPredicate::Always, "",
            "グリッドの間隔と副点の数を決めます。", false,
            {"AT-UIX-005"}},
        {"grid.move_origin", "グリッド原点を移動", CommandMode::Tool, "grid_origin", "",
            SelectionPredicate::Always, "",
            "グリッドの原点を、作図点や幾何点へ合わせます。", false,
            {"AT-UIX-005"}},
        {"guide.create", "形状ガイド", CommandMode::Dialog, "guide", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "選んだ線から形状ガイドを作ります。作れない入力は理由を出して断ります。", true,
            {"AT-GEO-001", "AT-GEO-002", "AT-GEO-003", "AT-GEO-004", "AT-GEO-005", "AT-GEO-006", "AT-UIX-007"}},
        {"wire.project", "面へ投影", CommandMode::Tool, "project", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "線を作業平面や面へ投影します。", true,
            {"AT-FAB-007"}},
        {"part.extrude", "押し出し", CommandMode::Dialog, "extrude", "X",
            SelectionPredicate::OneOrMoreClosedProfiles, "閉じた輪郭を1つ以上選んでください。",
            "輪郭を押し出します。出来る体積と面の数を先に出します。", true,
            {"AT-EXT-001", "AT-EXT-002", "AT-EXT-003", "AT-EXT-004", "AT-EXT-005", "AT-EXT-006", "AT-EXT-007", "AT-EXT-008"}},
        {"part.from_wire_cage", "ワイヤー群から部品", CommandMode::Dialog, "cage", "",
            SelectionPredicate::OneOrMoreWires, "ワイヤーを1つ以上選んでください。",
            "閉じたワイヤーのかごから部品を作ります。", true,
            {"AT-GEO-010", "AT-GEO-011", "AT-GEO-012", "AT-GEO-013"}},
        {"part.boolean_add", "足す", CommandMode::Dialog, "boolean_add", "",
            SelectionPredicate::TwoParts, "部品を2つ選んでください。",
            "部品に足します。離ればなれになるなら断ります。", true,
            {"AT-EXT-007"}},
        {"part.boolean_cut", "引く", CommandMode::Dialog, "boolean_cut", "",
            SelectionPredicate::TwoParts, "部品を2つ選んでください。",
            "部品から引きます。分かれる場合は個数を先に知らせます。", true,
            {"AT-EXT-007"}},
        {"derived.freeze", "現在状態を固定", CommandMode::Instant, "freeze", "",
            SelectionPredicate::OneDerivedEntity, "派生したものを1つ選んでください。",
            "派生したものを固定して、独立した実体にします。", true,
            {"AT-DOC-004", "AT-FAB-014"}},
        {"fabrication.create", "製作モデルを作る", CommandMode::Dialog, "fab_new", "",
            SelectionPredicate::OnePartOrSurface, "部品か形状ガイドを1つ選んでください。",
            "部品から製作モデルを作ります。元の部品は変えません。", true,
            {"AT-FAB-001", "AT-FAB-002", "AT-FAB-003", "AT-FAB-004", "AT-FAB-005"}},
        {"fabrication.assign_role", "境界の役割", CommandMode::Dialog, "fab_role", "",
            SelectionPredicate::OneFabricationPanel, "部材を1つ選んでください。",
            "部材の役割を手で決めます。", true,
            {"AT-FAB-006"}},
        {"fabrication.preview_update", "プレビュー更新", CommandMode::Instant, "fab_update", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "元の部品の変更を製作モデルへ反映します。", true,
            {"AT-PER-001"}},
        {"fabrication.create_pattern", "型紙を作る", CommandMode::Dialog, "pattern", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "型紙を作ります。", true,
            {"AT-FAB-001"}},
        {"fabrication.set_assembly", "組立状態", CommandMode::Instant, "assembly", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "組み立ての途中の状態を決めます。", false,
            {"AT-FAB-009", "AT-FAB-010", "AT-FAB-011"}},
        {"fabrication.freeze_state", "現在状態を固定", CommandMode::Instant, "fab_freeze", "",
            SelectionPredicate::OneFabricationModel, "製作モデルを1つ選んでください。",
            "いまの状態を固定して、独立したワイヤーや部品にします。", true,
            {"AT-FAB-011"}},
        {"export.validate", "出力を検査", CommandMode::Instant, "validate", "",
            SelectionPredicate::OnePart, "部品を1つ選んでください。",
            "書き出せる形かどうかを先に確かめます。", false,
            {"AT-EXP-011"}},
        {"export.stl", "STLで保存", CommandMode::Dialog, "stl", "",
            SelectionPredicate::OnePart, "部品を1つ選んでください。",
            "STLで書き出します。", false,
            {"AT-EXP-010"}},
        {"export.step", "STEPで保存", CommandMode::Dialog, "step", "",
            SelectionPredicate::OnePart, "部品を1つ選んでください。",
            "STEPで書き出します。", false,
            {"AT-EXP-010"}},
        {"export.svg", "SVGで保存", CommandMode::Dialog, "svg", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙をSVGで書き出します。", false,
            {"AT-EXP-012"}},
        {"export.dxf", "DXFで保存", CommandMode::Dialog, "dxf", "",
            SelectionPredicate::OneOrMorePatterns, "型紙を1つ以上選んでください。",
            "型紙をDXFで書き出します。", false,
            {"AT-EXP-012"}},
    };
    return table;
}

const CommandDescriptor* FindCommand(std::string_view id)
{
    const auto& table = CommandCatalog();
    const auto found = std::find_if(table.begin(), table.end(),
        [id](const CommandDescriptor& item) { return item.id == id; });
    return found == table.end() ? nullptr : &*found;
}

} // namespace kachakacha::v2::app
