#include "CoreMessageJa.h"

#include <QHash>

#include <algorithm>
#include <vector>

namespace {

//! 英語の例外文 → 日本語。並びは英語の辞書順(重複を見つけやすいように)。
const std::vector<std::pair<const char*, const char*>>& Table()
{
    static const std::vector<std::pair<const char*, const char*>> table = {
        // 「<用途>」を差し込んで組み立てられる文。前方一致だと用途が英語で残るので、
        // 組み合わせを丸ごと並べる。
        {"Projected wire cannot be used as loft section.", "投影から作られた線はロフトの断面には使えません"},
        {"Projected wire cannot be used as planar surface boundary.", "投影から作られた線は平らな面の輪郭には使えません"},
        {"Projected wire cannot be used as first ruled-surface section.", "投影から作られた線はルールド面の1本目の断面には使えません"},
        {"Projected wire cannot be used as second ruled-surface section.", "投影から作られた線はルールド面の2本目の断面には使えません"},
        {"Projected wire cannot be used as guided-loft cross section.", "投影から作られた線はガイド付きロフトの断面には使えません"},
        {"Projected wire cannot be used as first guided-loft guide.", "投影から作られた線はガイド付きロフトの1本目のガイドには使えません"},
        {"Projected wire cannot be used as second guided-loft guide.", "投影から作られた線はガイド付きロフトの2本目のガイドには使えません"},
        {"Plate-offset wire cannot be used as loft section.", "オフセットの線はロフトの断面には使えません"},
        {"Plate-offset wire cannot be used as planar surface boundary.", "オフセットの線は平らな面の輪郭には使えません"},
        {"Plate-offset wire cannot be used as first ruled-surface section.", "オフセットの線はルールド面の1本目の断面には使えません"},
        {"Plate-offset wire cannot be used as second ruled-surface section.", "オフセットの線はルールド面の2本目の断面には使えません"},
        {"Plate-offset wire cannot be used as guided-loft cross section.", "オフセットの線はガイド付きロフトの断面には使えません"},
        {"Plate-offset wire cannot be used as first guided-loft guide.", "オフセットの線はガイド付きロフトの1本目のガイドには使えません"},
        {"Plate-offset wire cannot be used as second guided-loft guide.", "オフセットの線はガイド付きロフトの2本目のガイドには使えません"},
        {"Construction wire cannot be used as loft section.", "補助線はロフトの断面には使えません"},
        {"Construction wire cannot be used as planar surface boundary.", "補助線は平らな面の輪郭には使えません"},
        {"Construction wire cannot be used as first ruled-surface section.", "補助線はルールド面の1本目の断面には使えません"},
        {"Construction wire cannot be used as second ruled-surface section.", "補助線はルールド面の2本目の断面には使えません"},
        {"Construction wire cannot be used as guided-loft cross section.", "補助線はガイド付きロフトの断面には使えません"},
        {"Construction wire cannot be used as first guided-loft guide.", "補助線はガイド付きロフトの1本目のガイドには使えません"},
        {"Construction wire cannot be used as second guided-loft guide.", "補助線はガイド付きロフトの2本目のガイドには使えません"},
        {"loft section repeats source wire:", "同じ線をロフトの断面に2回使っています"},
        {"loft section wire is missing:", "ロフトの断面の線が見つかりません"},
        {"planar surface boundary repeats source wire:", "同じ線を平らな面の輪郭に2回使っています"},
        {"planar surface boundary wire is missing:", "平らな面の輪郭の線が見つかりません"},
        {"first ruled-surface section repeats source wire:", "同じ線をルールド面の1本目の断面に2回使っています"},
        {"first ruled-surface section wire is missing:", "ルールド面の1本目の断面の線が見つかりません"},
        {"second ruled-surface section repeats source wire:", "同じ線をルールド面の2本目の断面に2回使っています"},
        {"second ruled-surface section wire is missing:", "ルールド面の2本目の断面の線が見つかりません"},
        {"guided-loft cross section repeats source wire:", "同じ線をガイド付きロフトの断面に2回使っています"},
        {"guided-loft cross section wire is missing:", "ガイド付きロフトの断面の線が見つかりません"},
        {"first guided-loft guide repeats source wire:", "同じ線をガイド付きロフトの1本目のガイドに2回使っています"},
        {"first guided-loft guide wire is missing:", "ガイド付きロフトの1本目のガイドの線が見つかりません"},
        {"second guided-loft guide repeats source wire:", "同じ線をガイド付きロフトの2本目のガイドに2回使っています"},
        {"second guided-loft guide wire is missing:", "ガイド付きロフトの2本目のガイドの線が見つかりません"},
{"A circle requires two split points.", "円を分割するには点が2つ必要です"},
{"A closed circle cannot be extended.", "閉じた円は延長できません"},
{"A closed curve needs two boundary intersections to trim.", "閉じた曲線を切るには交点が2つ必要です"},
{"A curved-plate wire must come from a projected drawing:", "曲げ板材の線は投影図から作ってください"},
{"A derived wire cannot be used as another projection source.", "派生した線は別の投影の元には使えません"},
{"A flat-pattern path must contain at least three points.", "展開の輪郭には点が3つ以上必要です"},
{"A plate assembly guide must come from a projected drawing:", "板材の組立ガイドは投影図から作ってください"},
{"A plate opening could not be assigned to a papercraft piece:", "開口をどの展開の面にも割り当てられません"},
{"A plate opening crosses a manual papercraft split:", "開口が手動の展開の分割線と交差しています"},
{"A plate opening wire cannot be changed to construction:", "板材の開口の線は補助線にできません"},
{"A plate relief-cut wire cannot be changed to construction:", "板材の切れ目の線は補助線にできません"},
{"A plate split-line wire cannot be changed to construction:", "板材の分割線は補助線にできません"},
{"A plate-offset source wire cannot be changed to construction:", "板材オフセットの元の線は補助線にできません"},
{"A projection source wire cannot be changed to construction:", "投影の元の線は補助線にできません"},
{"A relief cut crosses a papercraft piece boundary:", "切れ目が展開の面の境界と交差しています"},
{"A selected wire closes onto itself and cannot be mixed into another chain.", "閉じた線は他のつながりに混ぜられません"},
{"A surface guide wire cannot be changed to construction:", "面のガイド線は補助線にできません"},
{"A surface source wire cannot be changed to construction:", "面の元の線は補助線にできません"},
{"A wire is not on the selected export plane:", "書き出す平面の上にない線があります"},
{"Adjacent surface sections must be separated.", "隣り合う面の断面は離してください"},
{"An angle constraint requires a source work plane.", "角度の指定には元の作業平面が必要です"},
{"An angle-constrained line must have planar length.", "角度を指定する線には平面上の長さが必要です"},
{"An angle-constrained line requires a source work plane:", "角度を指定する線には元の作業平面が必要です"},
{"An opening or relief cut cannot also be a plate split line:", "開口や切れ目は板材の分割線にできません"},
{"Approximation source cannot join its own connection scope:", "近似モデルの元は自分の接続範囲に入れられません"},
{"Arc axes contain a non-finite value.", "円弧の軸の値が正しくありません"},
{"Arc axes must not be parallel.", "円弧の2つの軸は平行にできません"},
{"Arc control point move is invalid.", "円弧の制御点をそこへは動かせません"},
{"Arc handle must remain away from its center.", "円弧のハンドルは中心から離してください"},
{"Arc radius must be at least half the endpoint distance.", "円弧の半径は両端の距離の半分以上にしてください"},
{"Arc radius must be positive.", "円弧の半径は正の値にしてください"},
{"Arc sweep angle must not be zero.", "円弧の角度を0にはできません"},
{"Arc tangent direction must lie in its drawing plane.", "円弧の接線の向きは作図する平面の上にしてください"},
{"Arc tangent followers must be open circular arcs.", "接線をそろえる相手は開いた円弧にしてください"},
{"Arc value contains a non-finite value.", "円弧の値が正しくありません"},
{"Assembly hinge vertex was not found.", "組立の折り目の頂点が見つかりません"},
{"Assembly-state model name must not be empty.", "組立状態のモデル名を入力してください"},
{"Assembly-state panel is collapsed.", "組立状態の板がつぶれています"},
{"Assembly-state panel thickness must be positive.", "組立状態の板の厚みは正の値にしてください"},
{"Assembly-state panels are incomplete.", "組立状態の板がそろっていません"},
{"Automatic sets are removed with their part model:", "自動の部材グループは近似モデルと一緒に消えます"},
{"Automatic sets cannot be renamed:", "自動の部材グループは名前を変えられません"},
{"B-spline control point", "スプラインの制御点"},
{"B-spline control point count", "スプラインの制御点の数"},
{"B-spline control point count must be an integer of at least four.", "スプラインの制御点は4つ以上の整数にしてください"},
{"B-spline knot", "スプラインの節点"},
{"B-spline knot contains a non-finite value.", "スプラインの節点の値が正しくありません"},
{"B-spline knot range must be positive.", "スプラインの節点の範囲は正の値にしてください"},
{"B-spline span did not reduce to a cubic Bezier segment.", "スプラインの区間をベジェ曲線に分けられません"},
{"Bezier chain must contain at least one segment.", "ベジェ曲線には区間が1つ以上必要です"},
{"Body analysis requires at least two samples per direction.", "実体の解析には各方向2点以上必要です"},
{"Body name already exists:", "同じ名前の実体がすでにあります"},
{"Body name does not exist:", "その名前の実体はありません"},
{"Body name must not be empty.", "実体の名前を入力してください"},
{"Body not found:", "実体が見つかりません"},
{"Body parameters must be finite.", "実体の値が正しくありません"},
{"Body source surface", "実体の元の面"},
{"Body source surface is missing.", "実体の元の面がありません"},
{"Body surface range must be a non-empty part of the source surface.", "実体の面の範囲は元の面の一部にしてください"},
{"Cannot create a WorkPlane from collinear points.", "一直線に並んだ点からは作業平面を作れません"},
{"Cannot normalize a near-zero vector.", "長さがほぼ0の向きは扱えません"},
{"Chamfer points are too close together.", "C面取りの点が近すぎます"},
{"Chamfer setback exceeds the retained line branch.", "C面取りの距離が残す辺より長すぎます"},
{"Chamfer setback must be positive.", "C面取りの距離は正の値にしてください"},
{"Circular arc has no remaining sweep to extend.", "この円弧はもう延長できません"},
{"Closed circles do not have editable endpoints.", "閉じた円には動かせる端点がありません"},
{"Closed polyline trimming is not available yet.", "閉じた折れ線の切り取りはまだ使えません"},
{"Coincidence anchor wire", "一致の基準になる線"},
{"Coincidence follower wire", "一致で動く方の線"},
{"Coincident endpoint constraints require open wires.", "端点を合わせるには開いた線が必要です"},
{"Coincident endpoint must be finite.", "合わせる端点の値が正しくありません"},
{"Coincident endpoint would leave its locked work plane.", "端点が固定した作業平面から外れます"},
{"Coincident endpoints must belong to different wires.", "合わせる端点は別々の線のものにしてください"},
{"Conflicting G1/G2 continuity constraints on wire:", "なめらかにつなぐ指定が食い違っています"},
{"Conflicting endpoint and dimensional constraints on wire:", "端点の指定と寸法の指定が食い違っています"},
{"Conflicting endpoint and smooth continuity constraints near wire:", "端点の指定となめらかさの指定が食い違っています"},
{"Connection surface name is already used:", "その面の名前はすでに使われています"},
{"Connection wire name is already used:", "その線の名前はすでに使われています"},
{"Construction wire cannot be an opening source:", "補助線は開口の元には使えません"},
{"Construction wire cannot be used as", "補助線は次の用途には使えません"},
{"Construction wire cannot be used as a Gordon surface guide.", "補助線はゴードン面のガイドには使えません"},
{"Construction wire cannot be used as a Gordon surface section.", "補助線はゴードン面の断面には使えません"},
{"Construction wire cannot be used as a plate opening:", "補助線は板材の開口には使えません"},
{"Construction wire cannot be used as a plate relief cut:", "補助線は板材の切れ目には使えません"},
{"Construction wire cannot be used as a plate split line:", "補助線は板材の分割線には使えません"},
{"Construction wire cannot be used as a projection source.", "補助線は投影の元には使えません"},
{"Construction wire cannot be used as a surface opening:", "補助線は面の開口には使えません"},
{"Continuous assembly piece contains no verification panel.", "連続した組立の部品に確認用の板がありません"},
{"Continuous assembly section needs at least four points.", "連続した組立の断面には点が4つ以上必要です"},
{"Cubic B-spline internal knot multiplicity is too high.", "スプラインの内側の節点が重なりすぎです"},
{"Cubic B-spline knot count does not match its control points.", "スプラインの節点の数と制御点の数が合いません"},
{"Cubic B-spline knots must be finite and nondecreasing.", "スプラインの節点は小さい順に並べてください"},
{"Cubic B-spline must be clamped at both ends.", "スプラインは両端を固定してください"},
{"Cubic B-spline wire requires at least four control points.", "スプラインには制御点が4つ以上必要です"},
{"Cubic B-spline wire requires different start and end points.", "スプラインの始点と終点は別の位置にしてください"},
{"Cubic Bezier wire requires different start and end points.", "ベジェ曲線の始点と終点は別の位置にしてください"},
{"Curvature anchor handle must have a non-zero length.", "曲がり具合の基準ハンドルに長さが必要です"},
{"Curvature anchor must have a non-zero endpoint tangent.", "曲がり具合の基準に端点の接線の向きが必要です"},
{"Curvature direction would leave the follower work plane.", "曲がりの向きが相手の作業平面から外れます"},
{"Curve chord tolerance must be positive.", "曲線の分割の細かさは正の値にしてください"},
{"Curve endpoint has no stable direction to extend.", "曲線の端点に延長できる向きがありません"},
{"C面取りの距離が辺の長さを超えています。", "C面取りの距離が辺の長さを超えています"},
{"C面取りの距離は正の値で指定してください。", "C面取りの距離は正の値にしてください"},
{"Default object set", "既定の部材グループ"},
{"Delete plate-offset wire before splitting this plate:", "板材を分割する前にオフセットの線を消してください"},
{"Dependent surface is missing:", "必要な面がありません"},
{"Dependent wire is missing:", "必要な線がありません"},
{"Derived surfaces cannot join a connection scope:", "派生した面は接続範囲に入れられません"},
{"Derived wire metadata is controlled by its source geometry.", "派生した線の設定は元の形で決まります"},
{"Derived wire must be edited through its source geometry.", "派生した線は元の形から編集してください"},
{"Derived wires cannot join a connection scope:", "派生した線は接続範囲に入れられません"},
{"Developability analysis requires at least two samples per direction.", "展開できるかの確認には各方向2点以上必要です"},
{"Dimension plane reference", "寸法の基準の平面"},
{"Dimension wire reference", "寸法の基準の線"},
{"Each guided-loft cross section must touch both guide wires within the connection tolerance.", "ガイド付きロフトの断面は両方のガイドに接してください"},
{"Endpoint coincidence conflicts with the line work plane:", "端点を合わせると線の作業平面と食い違います"},
{"Endpoint coincidence constraints cannot form a cycle.", "端点を合わせる指定が輪になっています"},
{"Endpoint coincidence constraints did not converge.", "端点を合わせる計算がまとまりません"},
{"Endpoint coincidence wire is missing.", "端点を合わせる相手の線がありません"},
{"Endpoint tangent wire is missing.", "端点の接線の相手の線がありません"},
{"Endpoint-radius arc definition is invalid.", "両端と半径から円弧を作れません"},
{"Endpoint-radius arc requires two different endpoints.", "両端と半径の円弧には別々の端点が必要です"},
{"Exact spline offset is not supported yet.", "スプラインの正確なオフセットはまだ使えません"},
{"Expected count for", "数が読み取れません"},
{"Expected name for", "名前が読み取れません"},
{"Expected number for", "数値が読み取れません"},
{"Expected project format version.", "ファイル形式のバージョンが読み取れません"},
{"Extend pick parameter must lie on the target wire.", "延長する位置は相手の線の上にしてください"},
{"Extend tolerance must be positive.", "延長の許容値は正の値にしてください"},
{"Extrude source wire", "押し出しの元の線"},
{"Extrude source wire is missing:", "押し出しの元の線がありません"},
{"Extrude target surface", "押し出し先の面"},
{"Extrude target surface is missing:", "押し出し先の面がありません"},
{"Extruded wire", "押し出した線"},
{"Failed to write DXF output.", "DXFを書き出せませんでした"},
{"Failed to write SVG output.", "SVGを書き出せませんでした"},
{"Failed to write plate flat-pattern DXF.", "板材の展開のDXFを書き出せませんでした"},
{"Failed to write plate flat-pattern SVG.", "板材の展開のSVGを書き出せませんでした"},
{"Fillet arc sweep is too small.", "R面取りの円弧が小さすぎます"},
{"Fillet branches must form a usable corner angle.", "R面取りできる角の形になっていません"},
{"Fillet radius must be positive.", "R面取りの半径は正の値にしてください"},
{"Final B-spline span did not reduce to a cubic Bezier segment.", "スプラインの最後の区間をベジェ曲線に分けられません"},
{"Flat-pattern model name must not be empty.", "展開のモデル名を入力してください"},
{"Flat-pattern source wire was not found:", "展開の元の線が見つかりません"},
{"Gordon guide wires must not be repeated:", "ゴードン面のガイド線が重複しています"},
{"Gordon section wires must not be repeated:", "ゴードン面の断面線が重複しています"},
{"Gordon surface currently supports open section wires only.", "ゴードン面の断面は今は開いた線だけ使えます"},
{"Gordon surface guide wires must be open.", "ゴードン面のガイド線は開いた線にしてください"},
{"Gordon surface intersection tolerance must be positive.", "ゴードン面の交点の許容値は正の値にしてください"},
{"Gordon surface requires at least one guide wire.", "ゴードン面にはガイド線が1本以上必要です"},
{"Gordon surface requires at least two section wires.", "ゴードン面には断面線が2本以上必要です"},
{"Gordon surface wire cannot be used as both a section and a guide:", "同じ線を断面とガイドの両方には使えません"},
{"Guide wire", "ガイドの線"},
{"Guide wires must cross every section in the same order.", "ガイド線はどの断面も同じ順に横切ってください"},
{"Guided loft cross sections must be open wires.", "ガイド付きロフトの断面は開いた線にしてください"},
{"Guided loft guides must be open and the connection tolerance must be positive.", "ガイドは開いた線に、許容値は正の値にしてください"},
{"Guided loft parameter data is incomplete.", "ガイド付きロフトの設定がそろっていません"},
{"Guided loft parameter map is incomplete.", "ガイド付きロフトの対応付けがそろっていません"},
{"Guided loft requires at least one cross section.", "ガイド付きロフトには断面が1つ以上必要です"},
{"Guided loft requires two different guides and at least one cross section.", "別々のガイド2本と断面1つ以上が必要です"},
{"Guided loft source groups are incomplete.", "ガイド付きロフトの元のまとまりがそろっていません"},
{"Guided-loft cross sections cross or occupy the same guide position.", "断面どうしが交差か同じ位置にあります"},
{"Guided-loft wires must not be repeated:", "ガイド付きロフトの線が重複しています"},
{"Inserted B-spline knot was not found.", "追加したスプラインの節点が見つかりません"},
{"Interpolating cubic B-spline requires at least four through-points.", "通過点は4つ以上必要です"},
{"Interpolating cubic B-spline requires different start and end points.", "通る始点と終点は別の位置にしてください"},
{"Intersection is outside a line segment.", "交点が線の範囲の外にあります"},
{"Invalid number for", "数値が正しくありません"},
{"Jig clearance must be a non-negative finite value.", "治具のすき間は0以上の数値にしてください"},
{"Jig side is invalid.", "治具の向きが正しくありません"},
{"Jig source surface does not exist:", "治具の元になる面がありません"},
{"Jig thickness must be a positive finite value.", "治具の厚みは0より大きい数値にしてください"},
{"Join requires at least one wire.", "つなぐには線を1本以上選んでください"},
{"Join requires open wires.", "つなげるのは閉じていない線だけです"},
{"Join tolerance must be positive.", "つなぐ許容値は0より大きくしてください"},
{"Laminate base must use a one-sided thickness direction (not centered):", "貼り重ねの土台は厚みを片側に付けてください"},
{"Laminate base plate", "貼り重ねの土台の板材"},
{"Laminate base plate does not exist:", "貼り重ねの土台の板材がありません"},
{"Laminate base plate is missing:", "貼り重ねの土台の板材が見つかりません"},
{"Laminate relation would create a cycle:", "貼り重ねが輪になってしまいます"},
{"Laminated plate must use the same thickness direction as its base.", "貼り重ねる板材は土台と厚みの向きをそろえてください"},
{"Laminating onto a variable-thickness plate is not supported yet:", "厚みが変わる板材には貼り重ねできません"},
{"Line constraint angle must be finite.", "直線の角度は数値で入力してください"},
{"Line constraint length must be positive.", "直線の長さは0より大きくしてください"},
{"Line constraint tolerance must be positive.", "直線の許容値は0より大きくしてください"},
{"Line constraints can only be applied to a line wire.", "角度や長さの指定は直線の線にだけ使えます"},
{"Line constraints require a non-zero line.", "長さが0の線には指定できません"},
{"Line intersection editing requires two line wires.", "交点の編集には直線の線が2本必要です"},
{"Line intersection tolerance must be positive.", "交点の許容値は0より大きくしてください"},
{"Line intersection would create a zero-length wire.", "交点を作ると長さが0の線になります"},
{"Line wire requires two different points.", "直線には違う2つの点が必要です"},
{"Lines are parallel or nearly parallel.", "2本の線がほぼ平行です"},
{"Lines do not intersect in 3D.", "2本の線は立体の中で交わっていません"},
{"Loft section wires must not be repeated:", "ロフトの断面の線が重なって指定されています"},
{"Loft surface requires at least three section wires.", "ロフト面には断面の線が3本以上必要です"},
{"Loft surface requires at least three sections.", "ロフト面には断面が3つ以上必要です"},
{"Measurement parameter must be finite.", "測定の値は数値で入力してください"},
{"Measurement point must be finite.", "測定する点の位置が正しくありません"},
{"Measurement tolerance must be positive.", "測定の許容値は0より大きくしてください"},
{"Name already exists:", "同じ名前がすでにあります"},
{"New name must not be empty.", "新しい名前を入力してください"},
{"New set name must not be empty.", "新しい部材グループの名前を入力してください"},
{"No model wires were selected for planar export.", "展開に出す模型の線が選ばれていません"},
{"No safe seam remains between openings on this closed surface.", "開口の間に切り開ける場所が残っていません"},
{"No visible wire boundary intersects the target.", "そこと交わる線の境目が見つかりません"},
{"No visible wire boundary lies in the selected extension direction.", "伸ばす向きに線の境目がありません"},
{"No wires were selected for planar export.", "展開に出す線が選ばれていません"},
{"Offset arc must lie on the selected work plane.", "オフセットする円弧は作業平面の上に置いてください"},
{"Offset corner is too sharp for a stable miter.", "角が鋭すぎてオフセットできません"},
{"Offset distance collapses the circle or arc.", "オフセット量が大きすぎて円や円弧が消えます"},
{"Offset distance must be non-zero.", "オフセット量に0は使えません"},
{"Offset tolerance must be positive.", "オフセットの許容値は0より大きくしてください"},
{"Offset wire contains a zero-length segment.", "オフセットした線に長さ0の部分があります"},
{"Offset wire does not contain enough distinct points.", "オフセットする線の点が足りません"},
{"Offset wire must lie on the selected work plane.", "オフセットする線は作業平面の上に置いてください"},
{"Offset wire reverses direction at a vertex.", "オフセットした線が角で折り返しています"},
{"Opening projection direction must be valid.", "開口を投影する向きが正しくありません"},
{"Opening source wire must be closed:", "開口の元の線は閉じた線にしてください"},
{"Papercraft boundary could not be ordered.", "展開の外形線をつなげませんでした"},
{"Papercraft boundary is open.", "展開の外形線が閉じていません"},
{"Papercraft piece has no boundary.", "展開の部品に外形線がありません"},
{"Part model", "近似モデル"},
{"Part model is missing:", "近似モデルが見つかりません"},
{"Part model not found:", "近似モデルが見つかりません"},
{"Part number is out of range.", "部品の番号が範囲の外です"},
{"Part surface is used by body (remove the body first):", "実体で使われています。先に実体を消してください"},
{"Part surface is used by plate (remove the plate first):", "板材で使われています。先に板材を消してください"},
{"Part surface is used by plate:", "板材で使われている面です"},
{"Part-model boundary wire name is already used:", "近似モデルの外形線に同じ名前があります"},
{"Part-model boundary wires cannot be removed individually:", "近似モデルの外形線は1本ずつ消せません"},
{"Part-model derived surfaces cannot be approximated again:", "近似モデルから作られた面はもう近似できません"},
{"Part-model derived surfaces cannot be renamed directly:", "近似モデルから作られた面は名前を変えられません"},
{"Part-model derived surfaces manage openings automatically:", "近似モデルの面は開口を自動で扱います"},
{"Part-model derived wires cannot be an opening source:", "近似モデルから作られた線は開口の元に使えません"},
{"Part-model derived wires cannot be renamed directly:", "近似モデルから作られた線は名前を変えられません"},
{"Part-model edge wire name is already used:", "近似モデルの辺の線に同じ名前があります"},
{"Part-model name already exists:", "同じ名前の近似モデルがすでにあります"},
{"Part-model name does not exist:", "その名前の近似モデルはありません"},
{"Part-model name must not be empty.", "近似モデルの名前を入力してください"},
{"Part-model opening source wire", "近似モデルの開口の元の線"},
{"Part-model opening wire name is already used:", "近似モデルの開口の線に同じ名前があります"},
{"Part-model rail wire is missing.", "近似モデルの案内の線が見つかりません"},
{"Part-model scope surface", "近似モデルの対象の面"},
{"Part-model scope wire", "近似モデルの対象の線"},
{"Part-model source plate", "近似モデルの元の板材"},
{"Part-model source plate is missing:", "近似モデルの元の板材が見つかりません"},
{"Part-model source surface", "近似モデルの元の面"},
{"Part-model source surface is missing:", "近似モデルの元の面が見つかりません"},
{"Part-model split axis must be u or v.", "近似モデルの分割の向きはuかvにしてください"},
{"Part-model surface name is already used:", "近似モデルの面に同じ名前があります"},
{"Part-model surfaces cannot be removed individually:", "近似モデルの面は1つずつ消せません"},
{"Planar export options must contain valid positive tolerances and margin.", "展開の許容値と余白は0より大きくしてください"},
{"Planar plate ranges are not supported.", "平らな板材では範囲の指定は使えません"},
{"Planar plates can already be cut directly and do not need surface splitting.", "平らな板材はそのまま切れるので面を分ける必要はありません"},
{"Planar surface boundary crosses or overlaps itself.", "面の外形線が自分と交わっています"},
{"Planar surface boundary does not contain enough distinct edges.", "面の外形線の辺が足りません"},
{"Planar surface boundary is not planar.", "外形線が同じ平面にのっていません"},
{"Planar surface boundary must enclose an area.", "外形線が面積を囲んでいません"},
{"Planar surface must contain one boundary group.", "平らな面の外形線は1つのまとまりにしてください"},
{"Planar surface requires a closed boundary wire.", "平らな面には閉じた外形線が必要です"},
{"Planar surface requires at least one boundary wire.", "平らな面には外形線が1本以上必要です"},
{"Plane distance dimensions require parallel work planes.", "面の間の寸法は平行な作業平面どうしで測ってください"},
{"Plate assembly guide belongs to a different source surface:", "組立ガイドの元の面が違います"},
{"Plate assembly guide collapsed to a point:", "組立ガイドが1つの点につぶれています"},
{"Plate assembly guide lies outside the selected plate piece:", "組立ガイドが選んだ板材の外にあります"},
{"Plate assembly progress must be finite.", "組立の進み具合の値が正しくありません"},
{"Plate base offset must be a finite value.", "板材の基準オフセットは数値で入力してください"},
{"Plate boundary produced non-finite coordinates.", "板材の外形線の座標を正しく出せませんでした"},
{"Plate cannot laminate onto itself:", "同じ板材には貼り重ねできません"},
{"Plate development accumulated too much local distortion.", "ゆがみが大きすぎて展開できません"},
{"Plate development contains a collapsed edge.", "展開の途中で辺がつぶれました"},
{"Plate development triangle adjacency is invalid.", "展開の三角形のつながりが正しくありません"},
{"Plate flat pattern contains a collapsed cutting edge.", "展開につぶれた切り線があります"},
{"Plate flat pattern contains a self-intersecting cutting boundary.", "展開の切り線が自分と交わっています"},
{"Plate flat pattern contains an unusable open path.", "展開に使えない開いた線があります"},
{"Plate flat pattern contains an unusable opening boundary.", "展開に使えない開口の線があります"},
{"Plate flat pattern contains invalid coordinates.", "展開の座標が正しくありません"},
{"Plate flat pattern has no usable closed outer boundary.", "展開に使える閉じた外形線がありません"},
{"Plate flat-pattern options are invalid.", "展開の設定が正しくありません"},
{"Plate is used as laminate base by:", "この板材を土台に貼り重ねているものがあります"},
{"Plate is used by offset wire:", "オフセットの線で使われている板材です"},
{"Plate is used by part model:", "近似モデルで使われている板材です"},
{"Plate material", "板材の材質"},
{"Plate material must not be empty.", "板材の材質を入力してください"},
{"Plate name already exists:", "同じ名前の板材がすでにあります"},
{"Plate name does not exist:", "その名前の板材はありません"},
{"Plate name must not be empty.", "板材の名前を入力してください"},
{"Plate not found:", "板材が見つかりません"},
{"Plate offset produced non-finite coordinates.", "オフセットの座標を正しく出せませんでした"},
{"Plate offset source lies outside this plate piece:", "オフセットの元の線が板材の外にあります"},
{"Plate offset source must be a wire projected to the plate source surface:", "オフセットの元は板材の面に投影した線にしてください"},
{"Plate offset wire collapsed to fewer than two points.", "オフセットの線が点1つにつぶれました"},
{"Plate offset wire name must not be empty.", "オフセットの線の名前を入力してください"},
{"Plate opening cannot also be a relief cut:", "開口と切れ目は同じ線にできません"},
{"Plate opening lies outside this plate piece:", "開口が板材の外にあります"},
{"Plate opening moved outside split piece:", "分けた板材の外に開口が出ました"},
{"Plate opening must be a wire projected to the plate source surface:", "開口は板材の面に投影した線にしてください"},
{"Plate opening projection relation is missing.", "開口の投影の情報がありません"},
{"Plate opening wire", "板材の開口の線"},
{"Plate opening wire must be closed:", "開口の線は閉じた線にしてください"},
{"Plate range does not contain opening:", "板材の範囲に開口が入っていません"},
{"Plate range does not contain relief cut:", "板材の範囲に切れ目が入っていません"},
{"Plate range does not contain split line:", "板材の範囲に分割線が入っていません"},
{"Plate relief cut cannot also be an opening:", "切れ目と開口は同じ線にできません"},
{"Plate relief cut lies outside this plate piece:", "切れ目が板材の外にあります"},
{"Plate relief cut moved outside split piece:", "分けた板材の外に切れ目が出ました"},
{"Plate relief cut must be a wire projected to the plate source surface:", "切れ目は板材の面に投影した線にしてください"},
{"Plate relief-cut projection relation is missing.", "切れ目の投影の情報がありません"},
{"Plate relief-cut wire", "板材の切れ目の線"},
{"Plate source surface", "板材の元の面"},
{"Plate source surface does not exist:", "板材の元の面がありません"},
{"Plate source surface has a degenerate interior region.", "板材の元の面につぶれた部分があります"},
{"Plate source surface is missing.", "板材の元の面が見つかりません"},
{"Plate split axis is invalid.", "板材の分割の向きが正しくありません"},
{"Plate split line cannot also be a relief cut:", "分割線と切れ目は同じ線にできません"},
{"Plate split line cannot also be an opening:", "分割線と開口は同じ線にできません"},
{"Plate split line coincides with opening:", "分割線が開口と重なっています"},
{"Plate split line coincides with relief cut:", "分割線が切れ目と重なっています"},
{"Plate split line crosses opening:", "分割線が開口を横切っています"},
{"Plate split line crosses relief cut:", "分割線が切れ目を横切っています"},
{"Plate split line lies outside this plate piece:", "分割線が板材の外にあります"},
{"Plate split line moved outside split piece:", "分けた板材の外に分割線が出ました"},
{"Plate split line must be a wire projected to the plate source surface:", "分割線は板材の面に投影した線にしてください"},
{"Plate split position must be between the two edges.", "分ける位置は両側の辺の間にしてください"},
{"Plate split-line wire", "板材の分割線"},
{"Plate start and end thickness must be positive finite values.", "板材の始めと終わりの厚みは0より大きくしてください"},
{"Plate surface contains disconnected or collapsed regions.", "板材の面が離れているかつぶれています"},
{"Plate surface has no developable area.", "板材の面に展開できる部分がありません"},
{"Plate surface is degenerate and cannot be analyzed.", "板材の面がつぶれていて調べられません"},
{"Plate surface range must be a non-empty part of the source surface.", "板材の範囲は元の面の一部を指定してください"},
{"Plate thickness causes the offset surface to fold or collapse.", "厚みが大きすぎて面が折れ込みます"},
{"Plate thickness direction is invalid.", "板材の厚みの向きが正しくありません"},
{"Plate thickness parameter must be finite.", "板材の厚みは数値で入力してください"},
{"Plate wire belongs to a different source surface:", "元の面が違う線です"},
{"Plate wire is not on its planar source surface:", "元の平らな面の上にない線です"},
{"Plate wire lies outside the selected plate piece:", "選んだ板材の外にある線です"},
{"Plate wire position must be between 0 and 1.", "線の位置は0から1の間にしてください"},
{"Plate-offset plate", "オフセットの元の板材"},
{"Plate-offset source wire", "オフセットの元の線"},
{"Plate-offset wire", "オフセットの線"},
{"Plate-offset wire cannot be used as", "オフセットの線は次の用途には使えません"},
{"Plate-offset wire cannot be used as a Gordon surface guide.", "オフセットの線はゴードン面のガイドに使えません"},
{"Plate-offset wire cannot be used as a Gordon surface section.", "オフセットの線はゴードン面の断面に使えません"},
{"Plate-offset wire target plate is missing.", "オフセットの線が付く板材が見つかりません"},
{"Point coordinates must be finite.", "点の座標が正しくありません"},
{"Point name already exists:", "すでに同じ名前の点があります"},
{"Point name does not exist:", "その名前の点が見つかりません"},
{"Point name must not be empty.", "点の名前を入力してください。"},
{"Point not found:", "点が見つかりません"},
{"Point source plane", "点のもとの作業平面"},
{"Point source plane does not exist:", "点のもとの作業平面がありません"},
{"Polyline wire has no measurable direction.", "折れ線の向きが決められません。"},
{"Polyline wire requires at least two points.", "折れ線には点が2つ以上必要です。"},
{"Project format version is specified more than once.", "ファイル形式の版が二重に書かれています。"},
{"Projected point is outside the planar surface boundary.", "投影した点が面の外にはみ出しています。"},
{"Projected wire", "投影から作られた線"},
{"Projected wire cannot be used as", "投影から作られた線は次には使えません"},
{"Projected wire cannot be used as a Gordon surface guide.", "投影から作られた線はゴードン面のガイドに使えません。"},
{"Projected wire cannot be used as a Gordon surface section.", "投影から作られた線はゴードン面の断面に使えません。"},
{"Projected wire collapsed to a point.", "投影した線が点につぶれました。"},
{"Projected wire name must not be empty.", "投影の線の名前を入力してください。"},
{"Projected wires cannot own endpoint coincidence constraints.", "投影から作られた線には端点一致の拘束を付けられません。"},
{"Projection direction and tolerance must be valid.", "投影の向きと許容値を正しく指定してください。"},
{"Projection direction is parallel to the planar surface.", "投影の向きが面と平行です。"},
{"Projection line does not intersect the surface.", "投影の線が面と交わりません。"},
{"Projection point, direction, and tolerance must be valid.", "投影の点・向き・許容値を正しく指定してください。"},
{"Projection points must be finite.", "投影する点の座標が正しくありません。"},
{"Projection source wire", "投影のもとの線"},
{"Projection surface does not exist:", "投影先の面がありません"},
{"Projection target surface", "投影先の面"},
{"Projection target surface is missing:", "投影先の面が見つかりません"},
{"Radius constraint must be positive.", "半径は正の値で指定してください。"},
{"Radius constraints can only be applied to circles and circular arcs.", "半径の拘束は円と円弧にだけ付けられます。"},
{"Radius dimensions require a circle or circular arc.", "半径の寸法には円か円弧が必要です。"},
{"Reference dimension", "参考寸法"},
{"Reference dimension name already exists:", "すでに同じ名前の参考寸法があります"},
{"Reference dimension name does not exist:", "その名前の参考寸法が見つかりません"},
{"Reference dimension name must not be empty.", "参考寸法の名前を入力してください。"},
{"Reference dimension point must be finite.", "参考寸法の点の座標が正しくありません。"},
{"Reference dimension requires a point or wire position.", "参考寸法には点か線の上の位置が必要です。"},
{"Reference dimension requires a valid wire reference.", "参考寸法には正しい線の指定が必要です。"},
{"Reference dimension requires a work plane reference.", "参考寸法には作業平面の指定が必要です。"},
{"Reference dimension work plane does not exist:", "参考寸法の作業平面がありません"},
{"Relief cut contains a collapsed segment.", "切れ目につぶれた部分があります。"},
{"Relief cut is too short to form a 3D slot.", "切れ目が短すぎて溝になりません。"},
{"Relief-cut width must be between 0 and 10 mm.", "切れ目の幅は0〜10mmで指定してください。"},
{"Remove papercraft split lines before replacing this plate with two plate objects.", "先に展開の分割線を消してから板材を2枚に分けてください。"},
{"Remove plate openings before changing the source surface.", "もとの面を変える前に板材の開口を消してください。"},
{"Remove plate relief cuts before changing the source surface.", "もとの面を変える前に板材の切れ目を消してください。"},
{"Remove plate split lines before changing the source surface.", "もとの面を変える前に板材の分割線を消してください。"},
{"Required minimum wall must be positive.", "最小の厚みは正の値で指定してください。"},
{"Ruled surface must contain two section groups.", "ルールド面には断面の組が2つ必要です。"},
{"Ruled surface requires two sections.", "ルールド面には断面が2つ必要です。"},
{"Ruled-surface source wire is repeated:", "ルールド面のもとの線が重複しています"},
{"R丸めの半径が大きすぎます(接点が辺からはみ出します)。", "R丸めの半径が大きすぎます(接点が辺からはみ出します)。"},
{"R丸めの半径は正の値で指定してください。", "R丸めの半径は正の値で指定してください。"},
{"R丸めの弦公差は正の値で指定してください。", "R丸めの弦公差は正の値で指定してください。"},
{"STLを書き出せませんでした:", "STLを書き出せませんでした"},
{"Scope surface does not exist:", "対象の面がありません"},
{"Scope surface is missing:", "対象の面が見つかりません"},
{"Scope wire does not exist:", "対象の線がありません"},
{"Scope wire is missing:", "対象の線が見つかりません"},
{"Selected assembly piece contains no panels.", "選んだ組立の部品に板材が1枚もありません。"},
{"Selected assembly piece is outside the available range.", "選んだ組立の部品は範囲の外です。"},
{"Selected continuous assembly piece contains no model.", "選んだ続きの組立の部品に形がありません。"},
{"Selected wires cannot be ordered into one continuous chain.", "選んだ線を1本につなげられません。"},
{"Selected wires contain a branch. Select one path between junctions.", "線が枝分かれしています。分かれ目の間の1本道を選んでください。"},
{"Selected wires contain a duplicate or overlapping segment.", "選んだ線に重なりや同じ線があります。"},
{"Selected wires do not form one open or closed endpoint chain.", "選んだ線が1本のつながりになっていません。"},
{"Selected wires form more than one disconnected chain.", "選んだ線が2つ以上に分かれています。"},
{"Set is missing:", "部材グループが見つかりません"},
{"Set member", "部材グループの中身"},
{"Set member kind is unknown:", "部材グループの中身の種類が分かりません"},
{"Set name already exists:", "すでに同じ名前の部材グループがあります"},
{"Set name must not be empty.", "部材グループの名前を入力してください。"},
{"Set not found:", "部材グループが見つかりません"},
{"Set state must be visible, reference, or hidden.", "部材グループの状態は表示・参照・非表示のどれかです。"},
{"Sketch point contains a non-finite value.", "点の座標が正しくありません。"},
{"Spline through-points could not be interpolated.", "指定した点を通るスプラインを作れません。"},
{"Split line does not cross the papercraft fold mesh:", "分割線が展開の折り目と交わりません"},
{"Split plate name already exists.", "その名前の板材はすでにあります。"},
{"Split plate names must be different and non-empty.", "分けた板材にはそれぞれ違う名前を付けてください。"},
{"Start-tangent arc definition is invalid.", "接線から始まる円弧の指定が正しくありません。"},
{"Surface and projected-wire dependencies contain a cycle.", "面と投影の線の参照が堂々巡りになっています。"},
{"Surface curvature is undefined at this position.", "この位置では面の曲がり方が決まりません。"},
{"Surface guide wire", "面のガイドの線"},
{"Surface is used by a part-model connection scope:", "その面は近似モデルのつなぎに使われています"},
{"Surface is used by body:", "その面は実体に使われています"},
{"Surface is used by part model:", "その面は近似モデルに使われています"},
{"Surface is used by plate:", "その面は板材に使われています"},
{"Surface is used by projected wire:", "その面は投影の線に使われています"},
{"Surface name already exists:", "すでに同じ名前の面があります"},
{"Surface name does not exist:", "その名前の面が見つかりません"},
{"Surface name must not be empty.", "面の名前を入力してください。"},
{"Surface normal is undefined in this region.", "この辺りでは面の向きが決まりません。"},
{"Surface not found:", "面が見つかりません"},
{"Surface opening must be a wire projected to this surface:", "開口にはこの面へ投影した線を使ってください"},
{"Surface opening wire", "面の開口の線"},
{"Surface opening wire must be closed:", "面の開口の線は閉じた線にしてください"},
{"Surface parameters must be finite.", "面の値が正しくありません。"},
{"Surface sections must all be open or all be closed.", "断面はすべて開いた線か、すべて閉じた線にしてください。"},
{"Surface source wire", "面のもとの線"},
{"Surface source wire is missing:", "面のもとの線が見つかりません"},
{"Tangent anchor wire", "接線のもとの線"},
{"Tangent direction would leave the follower work plane.", "接線の向きが相手の作業平面から外れます。"},
{"Tangent endpoint constraints require open, editable wires.", "端点の接線拘束には編集できる開いた線が必要です。"},
{"Tangent endpoints must belong to different wires.", "接線でつなぐ端点は別々の線のものにしてください。"},
{"Tangent endpoints must have a matching coincidence constraint.", "接線でつなぐ端点には一致の拘束も必要です。"},
{"Tangent follower handle must have a non-zero length.", "接線側の引き手の長さを0以外にしてください。"},
{"Tangent follower wire", "接線をそろえる線"},
{"Tangent followers must be Bezier or B-spline wires.", "接線をそろえる線はベジエかBスプラインにしてください。"},
{"Tangent followers must be Bezier, B-spline, or circular arc wires.", "接線をそろえる線はベジエ・Bスプライン・円弧にしてください。"},
{"The curvature follower must be a cubic Bezier wire.", "曲がり方をそろえる線は3次ベジエにしてください。"},
{"The follower endpoint already has a coincidence constraint.", "その端点にはすでに一致の拘束が付いています。"},
{"The follower endpoint already has a tangent constraint.", "その端点にはすでに接線の拘束が付いています。"},
{"The tangent follower must be a Bezier, B-spline, or circular arc wire.", "接線をそろえる線はベジエ・Bスプライン・円弧にしてください。"},
{"This wire kind cannot be extended.", "この種類の線は延長できません。"},
{"Three-point angle requires points away from its vertex.", "3点の角度は頂点から離れた点で指定してください。"},
{"Three-point arc could not determine a valid sweep.", "3点から円弧の向きが決まりません。"},
{"Three-point arc requires non-collinear points.", "3点が一直線では円弧を作れません。"},
{"Trim pick parameter must lie on the target wire.", "切り取る位置は対象の線の上で指定してください。"},
{"Trim tolerance must be positive.", "切り取りの許容値は正の値で指定してください。"},
{"Trim would remove the complete target wire.", "切り取ると線が丸ごと無くなります。"},
{"Trimmed curve portion is too short.", "切り取った後の線が短すぎます。"},
{"Two guide wires cross the sections at the same position.", "2本のガイドが同じ位置で断面と交わっています。"},
{"Unexpected extra token:", "余分な語があります"},
{"Unknown command:", "知らない命令です"},
{"Unknown dimension reference kind:", "寸法の参照の種類が分かりません"},
{"Unknown jig side:", "治具の側が分かりません"},
{"Unknown plate thickness direction:", "板材の厚みの向きが分かりません"},
{"Unknown reference dimension kind.", "参考寸法の種類が分かりません。"},
{"Unknown reference dimension kind:", "参考寸法の種類が分かりません"},
{"Unknown wire endpoint:", "線の端点が分かりません"},
{"Unknown wire kind.", "線の種類が分かりません。"},
{"Unknown wire plane policy:", "線の平面の扱いが分かりません"},
{"Unknown wire role:", "線の役割が分かりません"},
{"Unknown work plane:", "作業平面が分かりません"},
{"Unsupported project format version:", "対応していないファイル形式の版です"},
{"Updated plate surface does not contain opening:", "変えた後の板材の面に開口がありません"},
{"Updated plate surface does not contain relief cut:", "変えた後の板材の面に切れ目がありません"},
{"Updated plate surface does not contain split line:", "変えた後の板材の面に分割線がありません"},
{"Visibility object kind must be workplane, point, wire, surface, plate, body, or dimension.", "表示を切り替えられるのは作業平面・点・線・面・板材・実体・寸法だけです。"},
{"Visibility state must be shown or hidden.", "表示の状態は表示か非表示のどちらかです。"},
{"Wire constraint system did not converge.", "線の拘束を解けませんでした。"},
{"Wire control point move is invalid.", "制御点の動かし方が正しくありません。"},
{"Wire does not exist:", "その線がありません"},
{"Wire extraction range is invalid.", "取り出す範囲の指定が正しくありません。"},
{"Wire is already a plate opening:", "その線はすでに板材の開口です"},
{"Wire is already a plate relief cut:", "その線はすでに板材の切れ目です"},
{"Wire is already a plate split line:", "その線はすでに板材の分割線です"},
{"Wire is already a surface opening:", "その線はすでに面の開口です"},
{"Wire is already an opening of this part:", "その線はすでにこの部品の開口です"},
{"Wire is not a cubic B-spline.", "その線は3次Bスプラインではありません。"},
{"Wire is not a cubic Bezier segment.", "その線は3次ベジエではありません。"},
{"Wire is not a part opening:", "その線はこの部品の開口ではありません"},
{"Wire is not a relief cut of this plate:", "その線はこの板材の切れ目ではありません"},
{"Wire is not a split line of this plate:", "その線はこの板材の分割線ではありません"},
{"Wire is not a surface opening:", "その線は面の開口ではありません"},
{"Wire is not an arc or circle.", "その線は円弧でも円でもありません。"},
{"Wire is not an opening of this plate:", "その線はこの板材の開口ではありません"},
{"Wire is used as a part-model opening source:", "その線は近似モデルの開口のもとに使われています"},
{"Wire is used as a plate opening:", "その線は板材の開口に使われています"},
{"Wire is used as a plate relief cut:", "その線は板材の切れ目に使われています"},
{"Wire is used as a plate split line:", "その線は板材の分割線に使われています"},
{"Wire is used as a plate-offset source:", "その線は板材のオフセットのもとに使われています"},
{"Wire is used as a projection drawing:", "その線は投影図に使われています"},
{"Wire is used as a surface guide:", "その線は面のガイドに使われています"},
{"Wire is used as a surface opening:", "その線は面の開口に使われています"},
{"Wire is used by a part-model connection scope:", "その線は近似モデルのつなぎに使われています"},
{"Wire is used by an endpoint coincidence constraint.", "その線は端点一致の拘束に使われています。"},
{"Wire is used by an endpoint tangent constraint.", "その線は端点の接線拘束に使われています。"},
{"Wire is used by surface:", "その線は面に使われています"},
{"Wire mirror axis must lie in the mirror plane.", "鏡映の軸は鏡映する平面の上にしてください。"},
{"Wire mirror definition contains a non-finite value.", "鏡映の指定に正しくない値があります。"},
{"Wire name already exists:", "すでに同じ名前の線があります"},
{"Wire name does not exist:", "その名前の線が見つかりません"},
{"Wire name must not be empty.", "線の名前を入力してください。"},
{"Wire not found:", "線が見つかりません"},
{"Wire parameter must be finite.", "線の値が正しくありません。"},
{"Wire point contains a non-finite value.", "線の点の座標が正しくありません。"},
{"Wire rotation definition contains a non-finite value.", "線の回転の指定に正しくない値があります。"},
{"Wire source plane", "線のもとの作業平面"},
{"Wire source plane does not exist:", "線のもとの作業平面がありません"},
{"Wire split parameter must be inside the wire.", "分ける位置は線の内側で指定してください。"},
{"Wire translation contains a non-finite value.", "線の移動量が正しくありません。"},
{"Work plane", "作業平面"},
{"Work plane is used by an angle-constrained wire:", "その作業平面は角度を拘束した線に使われています"},
{"Work plane name already exists:", "すでに同じ名前の作業平面があります"},
{"Work plane name does not exist:", "その名前の作業平面が見つかりません"},
{"Work plane name must not be empty.", "作業平面の名前を入力してください。"},
{"Work plane not found:", "作業平面が見つかりません"},
{"WorkPlane input contains a non-finite value.", "作業平面の値が正しくありません。"},
{"WorkPlane rotation input contains a non-finite value.", "作業平面の回転の値が正しくありません。"},
{"WorkPlane translation contains a non-finite value.", "作業平面の移動量が正しくありません。"},
    };
    return table;
}

} // namespace

QString TranslateCoreMessage(const QString& text)
{
    if (text.isEmpty()) {
        return text;
    }
    // 既に日本語なら何もしない(UI層が自分で書いた文はそのまま出す)。
    const bool hasNonAscii = std::any_of(text.begin(), text.end(),
        [](QChar character) { return character.unicode() > 0x7F; });
    if (hasNonAscii) {
        return text;
    }

    static const QHash<QString, QString> exact = [] {
        QHash<QString, QString> map;
        for (const auto& [english, japanese] : Table()) {
            map.insert(QString::fromUtf8(english), QString::fromUtf8(japanese));
        }
        return map;
    }();
    const auto found = exact.constFind(text);
    if (found != exact.constEnd()) {
        return found.value();
    }

    // 「英語文: 名前」の形。いちばん長く一致する見出しを使う。
    QString bestJapanese;
    int bestLength = 0;
    for (const auto& [english, japanese] : Table()) {
        const QString key = QString::fromUtf8(english);
        if (key.size() > bestLength && text.startsWith(key)) {
            bestJapanese = QString::fromUtf8(japanese);
            bestLength = key.size();
        }
    }
    if (bestLength > 0) {
        return bestJapanese + text.mid(bestLength);
    }
    return text;
}
